export const templateDefault = {
  ROOT: {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: [],
    props: {
      customStyle: {
        padding: 10,
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
}

export const templateA = {
  ROOT: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['OWvKgKtCdT'],
    props: {
      responsive: { desktop: { customStyle: { padding: '0px 0px 0px 0px' } } },
      customStyle: { padding: '0px 0px 0px 0px' },
    },
    custom: { button: { label: 'deleteBlock' }, editing: true },
    hidden: false,
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  '0NWVIEm4x4': {
    type: { resolvedName: 'CraftSection' },
    nodes: ['prqTfGT73H', 'yJLab835NU', 'XB2Uk6uDFb', 'RHvlU8NCfE', 'NgKJ08GidG'],
    props: {
      responsive: { desktop: { customStyle: { padding: '0px 0px 0px 0px' } } },
      customStyle: { padding: '0px 0px 0px 0px' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'OWvKgKtCdT',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  '1wxn9jwBkZ': {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 40,
      height: 40,
      children: [],
      responsive: {
        desktop: {
          width: 40,
          height: 40,
          customStyle: {
            margin: '0px 0px 12px 0px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/8cabcc93-6db4-4952-8e34-b174460d3dee)',
          },
        },
      },
      customStyle: {
        margin: '0px 0px 12px 0px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/8cabcc93-6db4-4952-8e34-b174460d3dee)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '82-VtsCROL',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  '3VHO2tHQ7t': {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 40,
      height: 40,
      children: [],
      responsive: {
        desktop: {
          width: 40,
          height: 40,
          customStyle: {
            margin: '0px 0px 12px 0px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/8cabcc93-6db4-4952-8e34-b174460d3dee)',
          },
        },
      },
      customStyle: {
        margin: '0px 0px 12px 0px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/8cabcc93-6db4-4952-8e34-b174460d3dee)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'ukg4YWozXf',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  '3dKTtP4eb6': {
    type: { resolvedName: 'CraftParagraph' },
    nodes: [],
    props: {
      content:
        '但是什麼時候該理想，什麼時候該現實，什麼時候該堅持，什麼時候該妥協，又是一門藝術了，而這中間的拿捏，也是「初階的管理人才」與「進階的管理人才」之間的差別吧！但是什麼時候該理想，什麼時候該現實，什麼時候該堅持，什麼時候該妥協，又是一門藝術了，而這中間的拿捏，也是「初階的管理人才」與「進階的管理人才」之間的差別吧！',
      children: [],
      responsive: {
        desktop: {
          content:
            '但是什麼時候該理想，什麼時候該現實，什麼時候該堅持，什麼時候該妥協，又是一門藝術了，而這中間的拿捏，也是「初階的管理人才」與「進階的管理人才」之間的差別吧！但是什麼時候該理想，什麼時候該現實，什麼時候該堅持，什麼時候該妥協，又是一門藝術了，而這中間的拿捏，也是「初階的管理人才」與「進階的管理人才」之間的差別吧！',
          customStyle: {
            color: '#585858',
            margin: '16px 16px 16px 16px',
            fontSize: 16,
            textAlign: 'left',
            fontWeight: 'normal',
            lineHeight: 1.69,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '16px 16px 16px 16px',
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'JQZE76zLKh',
    isCanvas: false,
    displayName: '段落',
    linkedNodes: {},
  },
  '4Nwloed1Hy': {
    type: { resolvedName: 'CraftParagraph' },
    nodes: [],
    props: {
      content: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
      children: [],
      responsive: {
        desktop: {
          content: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            fontSize: 16,
            textAlign: 'left',
            fontWeight: 'normal',
            lineHeight: 1.69,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'ukg4YWozXf',
    isCanvas: false,
    displayName: '段落',
    linkedNodes: {},
  },
  '82-VtsCROL': {
    type: { resolvedName: 'CraftSection' },
    nodes: ['1wxn9jwBkZ', 'dHNmQ-mKcq', 'ZtNfn1IhsC'],
    props: {
      responsive: {
        desktop: {
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '32px 32px 32px 32px',
            background: '#fff',
            borderColor: '#e0e0e0',
            borderWidth: 0,
          },
        },
      },
      customStyle: {
        margin: '0px 0px 0px 0px',
        padding: '32px 32px 32px 32px',
        background: '#fff',
        borderColor: '#e0e0e0',
        borderWidth: 0,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'jtIMHcEtTW',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  '85x0NLl8wN': {
    type: { resolvedName: 'CraftSection' },
    nodes: ['tlLalqi7Qi', 'OpY3VX1jDH', 'PsjBKbK7bm'],
    props: {
      responsive: {
        desktop: {
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '32px 32px 32px 32px',
            background: '#fff',
            borderColor: '#e0e0e0',
            borderWidth: 0,
          },
        },
      },
      customStyle: {
        margin: '0px 0px 0px 0px',
        padding: '32px 32px 32px 32px',
        background: '#fff',
        borderColor: '#e0e0e0',
        borderWidth: 0,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'jtIMHcEtTW',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  '8Frn7EoVie': {
    type: { resolvedName: 'CraftSection' },
    nodes: [],
    props: {
      children: [],
      horizontal: false,
      responsive: {
        mobile: {
          children: [],
          horizontal: false,
          customStyle: {
            padding: '140px 0px 140px 0px',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/a2e6169f-c2ad-4be4-9c52-b7df940f24ec)',
          },
        },
        tablet: {
          children: [],
          horizontal: false,
          customStyle: {
            padding: '256px 0px 256px 0px',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/a2e6169f-c2ad-4be4-9c52-b7df940f24ec)',
          },
        },
        desktop: {
          children: [],
          horizontal: false,
          customStyle: {
            padding: '256px 0px 256px 0px',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/c45b3b4b-4e38-41d2-85ce-13d1b1af3718)',
          },
        },
      },
      customStyle: {
        padding: '256px 0px 256px 0px',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/a2e6169f-c2ad-4be4-9c52-b7df940f24ec)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'OWvKgKtCdT',
    isCanvas: false,
    displayName: '區塊',
    linkedNodes: {},
  },
  '8LBYQmkCIz': {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 40,
      height: 40,
      children: [],
      responsive: {
        desktop: {
          width: 40,
          height: 40,
          customStyle: {
            margin: '0px 0px 12px 0px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/8cabcc93-6db4-4952-8e34-b174460d3dee)',
          },
        },
      },
      customStyle: {
        margin: '0px 0px 12px 0px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/8cabcc93-6db4-4952-8e34-b174460d3dee)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'oJbxlkY-qR',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  An1D11d3Gb: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '屹立不搖的組織都有相同的模式',
      children: [],
      responsive: {
        desktop: {
          title: '屹立不搖的組織都有相同的模式',
          children: [],
          customStyle: {
            color: '#585858',
            margin: '16px 16px 16px 16px',
            padding: '0px 0px 0px 0px',
            fontSize: 24,
            textAlign: 'left',
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '16px 16px 16px 16px',
        padding: '0px 0px 0px 0px',
        fontSize: 24,
        textAlign: 'left',
        fontWeight: 'bold',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'JQZE76zLKh',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  D13JPeOzGN: {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 40,
      height: 40,
      children: [],
      responsive: {
        desktop: {
          width: 40,
          height: 40,
          customStyle: {
            margin: '0px 0px 12px 0px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/8cabcc93-6db4-4952-8e34-b174460d3dee)',
          },
        },
      },
      customStyle: {
        margin: '0px 0px 12px 0px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/8cabcc93-6db4-4952-8e34-b174460d3dee)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '_QwZqLY3Ct',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  DIVmgf6yBK: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['T_EU_Uqzg5', 'WllgJ9caYV', 'vNFJXXbgO1'],
    props: {
      responsive: {
        desktop: {
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '32px 32px 32px 32px',
            background: '#fff',
            borderColor: '#e0e0e0',
            borderWidth: 0,
          },
        },
      },
      customStyle: {
        margin: '0px 0px 0px 0px',
        padding: '32px 32px 32px 32px',
        background: '#fff',
        borderColor: '#e0e0e0',
        borderWidth: 0,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'jtIMHcEtTW',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  FAWftHFGAK: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '特色標題',
      children: [],
      responsive: {
        desktop: {
          title: '特色標題',
          customStyle: {
            color: '#585858',
            padding: '0px 0px 12px 0px',
            fontSize: 20,
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: { color: '#585858', padding: '0px 0px 12px 0px', fontSize: 20, fontWeight: 'bold', lineHeight: 1.5 },
    },
    custom: { editing: false },
    hidden: false,
    parent: '_QwZqLY3Ct',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  GWx1FAVl57: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '特色標題',
      children: [],
      responsive: {
        desktop: {
          title: '特色標題',
          customStyle: {
            color: '#585858',
            padding: '0px 0px 12px 0px',
            fontSize: 20,
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: { color: '#585858', padding: '0px 0px 12px 0px', fontSize: 20, fontWeight: 'bold', lineHeight: 1.5 },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'ukg4YWozXf',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  InHAgQOnBJ: {
    type: { resolvedName: 'CraftButton' },
    nodes: [],
    props: {
      link: '',
      size: 'lg',
      block: true,
      title: '馬上查看',
      variant: 'solid',
      children: [],
      openNewTab: false,
      responsive: {
        tablet: {
          link: '',
          size: 'lg',
          block: true,
          title: '馬上查看',
          variant: 'solid',
          children: [],
          openNewTab: false,
          customStyle: {
            color: '#fff',
            margin: '20px 0px 0px 0px',
            background: 'unset',
            borderColor: '#ffffff',
            borderWidth: 1,
          },
        },
        desktop: {
          link: '',
          size: 'lg',
          block: false,
          title: '馬上查看',
          variant: 'solid',
          children: [],
          openNewTab: false,
          customStyle: {
            color: '#fff',
            margin: '20px 0px 0px 0px',
            background: 'unset',
            borderColor: '#ffffff',
            borderWidth: 1,
          },
        },
      },
      customStyle: {
        color: '#fff',
        margin: '20px 0px 0px 0px',
        background: 'unset',
        borderColor: '#ffffff',
        borderWidth: 1,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'l5h75Ez-8C',
    isCanvas: false,
    displayName: '按鈕',
    linkedNodes: {},
  },
  JQZE76zLKh: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['An1D11d3Gb', '3dKTtP4eb6'],
    props: {
      responsive: {
        mobile: { customStyle: { margin: '0 0 5px 0', padding: '24px 0px 0px 0px', background: '#fff' } },
        tablet: { customStyle: { margin: '0 0 5px 0', padding: '24px 0px 0px 0px', background: '#fff' } },
        desktop: { customStyle: { margin: '0 0 5px 0', padding: '0px 0px 0px 0px', background: '#fff' } },
      },
      customStyle: { margin: '0 0 5px 0', padding: '0px 0px 0px 0px', background: '#fff' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'MM5pMMUP-Y',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  'MM5pMMUP-Y': {
    type: { resolvedName: 'CraftLayout' },
    nodes: ['JQZE76zLKh', 'dDHoplZLRM'],
    props: {
      ratios: [12],
      responsive: {
        mobile: { ratios: [12], customStyle: { padding: '0px 0px 0px 0px' } },
        tablet: { ratios: [12], customStyle: { padding: '0px 0px 0px 0px' } },
        desktop: { ratios: [6, 4], customStyle: { padding: '0px 0px 0px 0px' } },
      },
      customStyle: { padding: '0px 0px 0px 0px' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'RFUj2blctz',
    isCanvas: true,
    displayName: '佈局',
    linkedNodes: {},
  },
  NgKJ08GidG: {
    type: { resolvedName: 'CraftSection' },
    nodes: [],
    props: {
      children: [],
      responsive: {
        desktop: {
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '0px 0px 0px 0px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/07de0f91-332a-41bc-97b5-8ac6ea5af0af)',
          },
        },
      },
      customStyle: {
        margin: '0px 0px 0px 0px',
        padding: '0px 0px 0px 0px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/07de0f91-332a-41bc-97b5-8ac6ea5af0af)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '0NWVIEm4x4',
    isCanvas: false,
    displayName: '區塊',
    linkedNodes: {},
  },
  OWvKgKtCdT: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['8Frn7EoVie', 'RFUj2blctz', '0NWVIEm4x4'],
    props: { responsive: { desktop: { customStyle: { padding: 'px' } } }, customStyle: { padding: 'px' } },
    custom: { editing: false },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  OpY3VX1jDH: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '特色標題',
      children: [],
      responsive: {
        desktop: {
          title: '特色標題',
          customStyle: {
            color: '#585858',
            padding: '0px 0px 12px 0px',
            fontSize: 20,
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: { color: '#585858', padding: '0px 0px 12px 0px', fontSize: 20, fontWeight: 'bold', lineHeight: 1.5 },
    },
    custom: { editing: false },
    hidden: false,
    parent: '85x0NLl8wN',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  PsjBKbK7bm: {
    type: { resolvedName: 'CraftParagraph' },
    nodes: [],
    props: {
      content: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
      children: [],
      responsive: {
        desktop: {
          content: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            fontSize: 16,
            textAlign: 'left',
            fontWeight: 'normal',
            lineHeight: 1.69,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '85x0NLl8wN',
    isCanvas: false,
    displayName: '段落',
    linkedNodes: {},
  },
  RFUj2blctz: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['MM5pMMUP-Y'],
    props: {
      responsive: {
        tablet: { customStyle: { margin: '0px', padding: '40px 16px 40px 16px', background: '#fff' } },
        desktop: { customStyle: { margin: '0px 0px 0px 0px', padding: '64px 200px 64px 200px', background: '#fff' } },
      },
      customStyle: { margin: '0px', padding: '40px 16px 40px 16px', background: '#fff' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'OWvKgKtCdT',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  RHvlU8NCfE: {
    type: { resolvedName: 'CraftSection' },
    nodes: [],
    props: {
      children: [],
      responsive: {
        desktop: {
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '0px 0px 0px 0px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/07de0f91-332a-41bc-97b5-8ac6ea5af0af)',
          },
        },
      },
      customStyle: {
        margin: '0px 0px 0px 0px',
        padding: '0px 0px 0px 0px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/07de0f91-332a-41bc-97b5-8ac6ea5af0af)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '0NWVIEm4x4',
    isCanvas: false,
    displayName: '區塊',
    linkedNodes: {},
  },
  T_EU_Uqzg5: {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 40,
      height: 40,
      children: [],
      responsive: {
        desktop: {
          width: 40,
          height: 40,
          customStyle: {
            margin: '0px 0px 12px 0px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/8cabcc93-6db4-4952-8e34-b174460d3dee)',
          },
        },
      },
      customStyle: {
        margin: '0px 0px 12px 0px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/8cabcc93-6db4-4952-8e34-b174460d3dee)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'DIVmgf6yBK',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  WllgJ9caYV: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '特色標題',
      children: [],
      responsive: {
        desktop: {
          title: '特色標題',
          customStyle: {
            color: '#585858',
            padding: '0px 0px 12px 0px',
            fontSize: 20,
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: { color: '#585858', padding: '0px 0px 12px 0px', fontSize: 20, fontWeight: 'bold', lineHeight: 1.5 },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'DIVmgf6yBK',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  XB2Uk6uDFb: {
    type: { resolvedName: 'CraftSection' },
    nodes: [],
    props: {
      children: [],
      responsive: {
        desktop: {
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '0px 0px 0px 0px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/47ca1e35-09a0-452e-b34e-5ec0d4e3b4ca)',
          },
        },
      },
      customStyle: {
        margin: '0px 0px 0px 0px',
        padding: '0px 0px 0px 0px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/47ca1e35-09a0-452e-b34e-5ec0d4e3b4ca)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '0NWVIEm4x4',
    isCanvas: false,
    displayName: '區塊',
    linkedNodes: {},
  },
  XDd6bpKJni: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '還在等什麼？立即成為創作者',
      children: [],
      responsive: {
        tablet: {
          title: '還在等什麼？立即查看課程',
          children: [],
          customStyle: {
            color: '#ffffff',
            margin: 25,
            fontSize: 28,
            textAlign: 'center',
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
        desktop: {
          title: '還在等什麼？立即成為創作者',
          children: [],
          customStyle: {
            color: '#ffffff',
            margin: 25,
            fontSize: 28,
            textAlign: 'left',
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#ffffff',
        margin: 25,
        fontSize: 28,
        textAlign: 'left',
        fontWeight: 'bold',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'l5h75Ez-8C',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  ZtNfn1IhsC: {
    type: { resolvedName: 'CraftParagraph' },
    nodes: [],
    props: {
      content: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
      children: [],
      responsive: {
        desktop: {
          content: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            fontSize: 16,
            textAlign: 'left',
            fontWeight: 'normal',
            lineHeight: 1.69,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '82-VtsCROL',
    isCanvas: false,
    displayName: '段落',
    linkedNodes: {},
  },
  _Fa1tcrb2t: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '六大特色',
      children: [],
      responsive: {
        desktop: {
          title: '六大特色',
          customStyle: {
            color: '#585858',
            margin: 25,
            fontSize: 28,
            textAlign: 'center',
            fontWeight: 'bold',
            lineHeight: 1.2,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: 25,
        fontSize: 28,
        textAlign: 'center',
        fontWeight: 'bold',
        lineHeight: 1.2,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'prqTfGT73H',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  _QwZqLY3Ct: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['D13JPeOzGN', 'FAWftHFGAK', 'vVV453Cn-4'],
    props: {
      responsive: {
        desktop: {
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '32px 32px 32px 32px',
            background: '#fff',
            borderColor: '#e0e0e0',
            borderWidth: 0,
          },
        },
      },
      customStyle: {
        margin: '0px 0px 0px 0px',
        padding: '32px 32px 32px 32px',
        background: '#fff',
        borderColor: '#e0e0e0',
        borderWidth: 0,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'jtIMHcEtTW',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  dDHoplZLRM: {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 300,
      children: [],
      responsive: {
        desktop: {
          width: 300,
          customStyle: { backgroundImage: 'url("https://static.kolable.com/images/default/craft/image.png")' },
        },
      },
      customStyle: { backgroundImage: 'url("https://static.kolable.com/images/default/craft/image.png")' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'MM5pMMUP-Y',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  'dHNmQ-mKcq': {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '特色標題',
      children: [],
      responsive: {
        desktop: {
          title: '特色標題',
          customStyle: {
            color: '#585858',
            padding: '0px 0px 12px 0px',
            fontSize: 20,
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: { color: '#585858', padding: '0px 0px 12px 0px', fontSize: 20, fontWeight: 'bold', lineHeight: 1.5 },
    },
    custom: { editing: false },
    hidden: false,
    parent: '82-VtsCROL',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  iOYjc0rZD8: {
    type: { resolvedName: 'CraftParagraph' },
    nodes: [],
    props: {
      content: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
      children: [],
      responsive: {
        desktop: {
          content: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            fontSize: 16,
            textAlign: 'left',
            fontWeight: 'normal',
            lineHeight: 1.69,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'oJbxlkY-qR',
    isCanvas: false,
    displayName: '段落',
    linkedNodes: {},
  },
  jtIMHcEtTW: {
    type: { resolvedName: 'CraftLayout' },
    nodes: ['oJbxlkY-qR', 'DIVmgf6yBK', '_QwZqLY3Ct', '85x0NLl8wN', '82-VtsCROL', 'ukg4YWozXf'],
    props: {
      ratios: [12],
      responsive: {
        mobile: {
          ratios: [12],
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '0px 0px 0px 0px',
            borderColor: '#2D313A',
            borderWidth: 0,
          },
        },
        tablet: {
          ratios: [6, 6],
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '0px 0px 0px 0px',
            borderColor: '#2D313A',
            borderWidth: 0,
          },
        },
        desktop: {
          ratios: [4, 4, 4],
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '0px 0px 0px 0px',
            borderColor: '#2D313A',
            borderWidth: 0,
          },
        },
      },
      customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', borderColor: '#2D313A', borderWidth: 0 },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'prqTfGT73H',
    isCanvas: true,
    displayName: '佈局',
    linkedNodes: {},
  },
  'l5h75Ez-8C': {
    type: { resolvedName: 'CraftLayout' },
    nodes: ['XDd6bpKJni', 'InHAgQOnBJ'],
    props: {
      ratios: [12],
      responsive: {
        tablet: { ratios: [12], customStyle: { margin: '0px', padding: '40px 12px 40px 12px' } },
        desktop: { ratios: [7, 3], customStyle: { margin: '-px', padding: '64px 200px 64px 200px' } },
      },
      customStyle: { margin: '0px', padding: '40px 12px 40px 12px' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'yJLab835NU',
    isCanvas: true,
    displayName: '佈局',
    linkedNodes: {},
  },
  'oJbxlkY-qR': {
    type: { resolvedName: 'CraftSection' },
    nodes: ['8LBYQmkCIz', 'wWM3fLqLhZ', 'iOYjc0rZD8'],
    props: {
      responsive: {
        desktop: {
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '32px 32px 32px 32px',
            background: '#fff',
            borderColor: '#e0e0e0',
            borderWidth: 0,
          },
        },
      },
      customStyle: {
        margin: '0px 0px 0px 0px',
        padding: '32px 32px 32px 32px',
        background: '#fff',
        borderColor: '#e0e0e0',
        borderWidth: 0,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'jtIMHcEtTW',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  prqTfGT73H: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['_Fa1tcrb2t', 'jtIMHcEtTW'],
    props: {
      responsive: {
        mobile: { customStyle: { margin: '0px', padding: '40px 16px 40px 16px', background: '#fff' } },
        tablet: { customStyle: { margin: '0px', padding: '40px 16px 40px 16px', background: '#fff' } },
        desktop: {
          customStyle: { margin: '0px 0px 0px 0px', padding: '64px 200px 64px 200px', backgroundColor: '#f6f6f6' },
        },
      },
      customStyle: { margin: '0px 0px 0px 0px', padding: '64px 200px 64px 200px', backgroundColor: '#f6f6f6' },
    },
    custom: { editing: false },
    hidden: false,
    parent: '0NWVIEm4x4',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  tlLalqi7Qi: {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 40,
      height: 40,
      children: [],
      responsive: {
        desktop: {
          width: 40,
          height: 40,
          customStyle: {
            margin: '0px 0px 12px 0px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/8cabcc93-6db4-4952-8e34-b174460d3dee)',
          },
        },
      },
      customStyle: {
        margin: '0px 0px 12px 0px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/8cabcc93-6db4-4952-8e34-b174460d3dee)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '85x0NLl8wN',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  ukg4YWozXf: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['3VHO2tHQ7t', 'GWx1FAVl57', '4Nwloed1Hy'],
    props: {
      responsive: {
        desktop: {
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '32px 32px 32px 32px',
            background: '#fff',
            borderColor: '#e0e0e0',
            borderWidth: 0,
          },
        },
      },
      customStyle: {
        margin: '0px 0px 0px 0px',
        padding: '32px 32px 32px 32px',
        background: '#fff',
        borderColor: '#e0e0e0',
        borderWidth: 0,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'jtIMHcEtTW',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  vNFJXXbgO1: {
    type: { resolvedName: 'CraftParagraph' },
    nodes: [],
    props: {
      content: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
      children: [],
      responsive: {
        desktop: {
          content: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            fontSize: 16,
            textAlign: 'left',
            fontWeight: 'normal',
            lineHeight: 1.69,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'DIVmgf6yBK',
    isCanvas: false,
    displayName: '段落',
    linkedNodes: {},
  },
  'vVV453Cn-4': {
    type: { resolvedName: 'CraftParagraph' },
    nodes: [],
    props: {
      content: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
      children: [],
      responsive: {
        desktop: {
          content: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            fontSize: 16,
            textAlign: 'left',
            fontWeight: 'normal',
            lineHeight: 1.69,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '_QwZqLY3Ct',
    isCanvas: false,
    displayName: '段落',
    linkedNodes: {},
  },
  wWM3fLqLhZ: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '特色標題',
      children: [],
      responsive: {
        desktop: {
          title: '特色標題',
          customStyle: {
            color: '#585858',
            padding: '0px 0px 12px 0px',
            fontSize: 20,
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: { color: '#585858', padding: '0px 0px 12px 0px', fontSize: 20, fontWeight: 'bold', lineHeight: 1.5 },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'oJbxlkY-qR',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  yJLab835NU: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['l5h75Ez-8C'],
    props: {
      responsive: {
        desktop: {
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '0px 0px 0px 0px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/07de0f91-332a-41bc-97b5-8ac6ea5af0af)',
          },
        },
      },
      customStyle: {
        margin: '0px 0px 0px 0px',
        padding: '0px 0px 0px 0px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/07de0f91-332a-41bc-97b5-8ac6ea5af0af)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '0NWVIEm4x4',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
}

export const templateB = {
  ROOT: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['HekVEZhI_j'],
    props: {
      responsive: { desktop: { customStyle: { padding: '0px 0px 0px 0px' } } },
      customStyle: { padding: '0px 0px 0px 0px' },
    },
    custom: { button: { label: 'deleteBlock' }, editing: true },
    hidden: false,
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  '33X03hvb_L': {
    type: { resolvedName: 'CraftSection' },
    nodes: ['uWLUFjySF_', 'FM3L_jfRSn', 'iGBWeg3jtQ'],
    props: {
      className: '',
      responsive: {
        desktop: {
          className: '',
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '32px 24px 32px 24px',
            alignItems: 'center',
            background: '#fff',
          },
        },
      },
      customStyle: {
        margin: '0px 0px 0px 0px',
        padding: '32px 24px 32px 24px',
        alignItems: 'center',
        background: '#fff',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '_y_NfxWeVc',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  '33tWnxTRZE': {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 400,
      children: [],
      className: 'list-img',
      responsive: {
        desktop: {
          width: 400,
          className: 'list-img',
          customStyle: {
            width: '64px',
            height: '64px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/17823d0c-e4da-4b7c-ad4b-6ab9f1bc081a)',
          },
        },
      },
      customStyle: {
        width: '64px',
        height: '64px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/17823d0c-e4da-4b7c-ad4b-6ab9f1bc081a)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'rNCFA2NeEY',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  '39TTwEB6wU': {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 400,
      children: [],
      className: 'card-img',
      responsive: {
        mobile: {
          width: 400,
          className: 'card-img',
          customStyle: {
            width: '100%',
            height: '180px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/92bdba0c-9abd-489e-8269-60ee8618e66f)',
          },
        },
        tablet: {
          width: 400,
          className: 'card-img',
          customStyle: {
            width: '100%',
            height: '280px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/92bdba0c-9abd-489e-8269-60ee8618e66f)',
          },
        },
        desktop: {
          width: 400,
          className: 'card-img',
          customStyle: {
            width: '100%',
            height: '380px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/92bdba0c-9abd-489e-8269-60ee8618e66f)',
          },
        },
      },
      customStyle: {
        width: '100%',
        height: '180px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/92bdba0c-9abd-489e-8269-60ee8618e66f)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'Iit-mDGi28',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  '3l8vNg2PSg': {
    type: { resolvedName: 'CraftActivityCollection' },
    nodes: [],
    props: {
      layout: { gap: 1, columns: 1 },
      source: { from: 'custom', limit: 1, idList: ['e7191df3-1c6f-448d-ae11-a3e4d8997af0'] },
      variant: 'card',
      children: [],
      responsive: {
        desktop: {
          layout: { gap: 1, columns: 1 },
          source: { from: 'custom', limit: 1, idList: ['e7191df3-1c6f-448d-ae11-a3e4d8997af0'] },
          variant: 'card',
        },
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'Qq6IYoFZly',
    isCanvas: false,
    displayName: '活動',
    linkedNodes: {},
  },
  '3tOLTpWI-V': {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '立即領取專屬優惠',
      children: [],
      responsive: {
        desktop: {
          title: '立即領取專屬優惠',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            fontSize: 18,
            textAlign: 'left',
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        fontSize: 18,
        textAlign: 'left',
        fontWeight: 'bold',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'sMPx35ANUn',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  '4XgNI5fCph': {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '描述文字放置描述文字放置',
      children: [],
      responsive: {
        desktop: {
          title: '描述文字放置描述文字放置',
          customStyle: {
            color: '#9B9B9B',
            margin: '0px 0px 0px 0px',
            fontSize: 14,
            textAlign: 'left',
            fontWeight: 'normal',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#9B9B9B',
        margin: '0px 0px 0px 0px',
        fontSize: 14,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'e4mEe3yShu',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  DlsC29HXC1: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['tc24yklFH7'],
    props: {
      responsive: {
        mobile: {
          customStyle: {
            margin: '16px 0px 16px 0px',
            padding: '0px 0px 0px 0px',
            alignItems: 'start',
            background: '#fff',
            justifyContent: 'center',
          },
        },
      },
      customStyle: {
        margin: '16px 0px 16px 0px',
        padding: '0px 0px 0px 0px',
        alignItems: 'start',
        background: '#fff',
        justifyContent: 'center',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'R4mhx0ef8w',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  'DvYxH-Q436': {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 400,
      children: [],
      responsive: {
        tablet: {
          width: 400,
          customStyle: {
            width: '32px',
            height: '36px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/cb17cc05-118b-4970-b51e-60730430f56f)',
          },
        },
      },
      customStyle: {
        width: '32px',
        height: '36px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/cb17cc05-118b-4970-b51e-60730430f56f)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'ImkQ5l_1MO',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  FM3L_jfRSn: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '名稱',
      children: [],
      responsive: {
        desktop: {
          title: '名稱',
          customStyle: {
            color: '#585858',
            margin: '20px 4px 0px 4px',
            fontSize: 24,
            textAlign: 'center',
            fontWeight: 'bold',
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '20px 4px 0px 4px',
        fontSize: 24,
        textAlign: 'center',
        fontWeight: 'bold',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '33X03hvb_L',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  HekVEZhI_j: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['_y_NfxWeVc', 'wV7BNTlojc'],
    props: {
      responsive: {
        mobile: { customStyle: { padding: '0px 0px 20px 0px', backgroundColor: '#f8f8f8' } },
        desktop: { customStyle: { padding: '0px 0px 20px 0px', backgroundColor: '#f8f8f8' } },
      },
      customStyle: { padding: '0px 0px 20px 0px', backgroundColor: '#f8f8f8' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  'Iit-mDGi28': {
    type: { resolvedName: 'CraftSection' },
    nodes: ['39TTwEB6wU', 'R3OF6w9uFu'],
    props: {
      link: '',
      openTab: true,
      className: 'info-card',
      responsive: {
        mobile: {
          link: '/programs/104da8fc-97a4-478d-a643-c2a3708379d8',
          openTab: true,
          className: 'info-card',
          customStyle: {
            margin: '12px 0px 0px 0px',
            padding: 'ㄢpx 0px 0px 0px',
            alignItems: 'center',
            background: '#fff',
            justifyContent: 'center',
          },
        },
        desktop: {
          link: '',
          openTab: true,
          className: 'info-card',
          customStyle: {
            margin: '12px 0px 0px 0px',
            padding: 'ㄢpx 0px 0px 0px',
            alignItems: 'center',
            background: '#fff',
            justifyContent: 'center',
          },
        },
      },
      customStyle: {
        margin: '12px 0px 0px 0px',
        padding: 'ㄢpx 0px 0px 0px',
        alignItems: 'center',
        background: '#fff',
        justifyContent: 'center',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'wV7BNTlojc',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  ImkQ5l_1MO: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['DvYxH-Q436'],
    props: {
      className: '',
      responsive: {
        mobile: {
          className: '',
          customStyle: { margin: '0px 20px 0px 0px', padding: '0px 0px 0px 0px', background: '#fff' },
        },
      },
      customStyle: { margin: '0px 20px 0px 0px', padding: '0px 0px 0px 0px', background: '#fff' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'kqVKXRXJEO',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  'O-Y2DSlwB3': {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 400,
      children: [],
      responsive: {
        desktop: {
          width: 400,
          customStyle: {
            width: '20px',
            height: '20px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/b64228c2-6957-4137-a84b-80444ce51c98)',
          },
        },
      },
      customStyle: {
        width: '20px',
        height: '20px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/b64228c2-6957-4137-a84b-80444ce51c98)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'ugOFBDVO5F',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  OXPcKibkdP: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '項目標題名稱',
      children: [],
      responsive: {
        desktop: {
          title: '項目標題名稱',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            fontSize: 18,
            textAlign: 'left',
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        fontSize: 18,
        textAlign: 'left',
        fontWeight: 'bold',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'e4mEe3yShu',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  Qq6IYoFZly: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['_iTBONiroQ', '3l8vNg2PSg'],
    props: {
      responsive: {
        desktop: { customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: 'unset' } },
      },
      customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: 'unset' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'wV7BNTlojc',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  R3OF6w9uFu: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '項目標題名稱',
      children: [],
      responsive: {
        desktop: {
          title: '項目標題名稱',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            padding: '20px 20px 20px 20px',
            fontSize: 18,
            textAlign: 'center',
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        padding: '20px 20px 20px 20px',
        fontSize: 18,
        textAlign: 'center',
        fontWeight: 'bold',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'Iit-mDGi28',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  R4mhx0ef8w: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['DlsC29HXC1', 'ugOFBDVO5F'],
    props: {
      className: 'info-card list-layout',
      horizontal: true,
      responsive: {
        desktop: {
          className: 'info-card list-layout',
          horizontal: true,
          customStyle: {
            margin: '12px 0px 0px 0px',
            padding: '16px 24px 16px 24px',
            alignItems: 'center',
            background: '#fff',
          },
        },
      },
      customStyle: {
        margin: '12px 0px 0px 0px',
        padding: '16px 24px 16px 24px',
        alignItems: 'center',
        background: '#fff',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'wV7BNTlojc',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  UWAO_R2_Yc: {
    type: { resolvedName: 'CraftButton' },
    nodes: [],
    props: {
      link: '',
      size: 'lg',
      block: true,
      title: '馬上查看',
      variant: 'solid',
      children: [],
      openNewTab: false,
      responsive: {
        desktop: {
          link: '',
          size: 'lg',
          block: true,
          title: '馬上查看',
          variant: 'solid',
          openNewTab: false,
          customStyle: { color: '#fff', margin: '12px 0px 0px 0px', backgroundColor: '#585858' },
        },
      },
      customStyle: { color: '#fff', margin: '12px 0px 0px 0px', backgroundColor: '#585858' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'wV7BNTlojc',
    isCanvas: false,
    displayName: '按鈕',
    linkedNodes: {},
  },
  _iTBONiroQ: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '活動',
      children: [],
      responsive: {
        desktop: {
          title: '活動',
          customStyle: {
            color: '#585858',
            margin: '20px 4px 32px 4px',
            fontSize: 32,
            textAlign: 'center',
            fontWeight: 'bold',
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '20px 4px 32px 4px',
        fontSize: 32,
        textAlign: 'center',
        fontWeight: 'bold',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'Qq6IYoFZly',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  _y_NfxWeVc: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['33X03hvb_L'],
    props: {
      responsive: {
        mobile: {
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '0px 0px 0px 0px',
            background: 'unset',
            backgroundColor: '#fff',
          },
        },
        tablet: { customStyle: { margin: '0 0 5px 0', padding: '0px 100px 0px 100px', background: 'unset' } },
        desktop: {
          customStyle: { margin: '0px 0px 0px 0px', padding: '0px 400px 0px 400px', backgroundColor: '#fff' },
        },
      },
      customStyle: {
        margin: '0px 0px 0px 0px',
        padding: '0px 0px 0px 0px',
        background: 'unset',
        backgroundColor: '#fff',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'HekVEZhI_j',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  e4mEe3yShu: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['OXPcKibkdP', '4XgNI5fCph'],
    props: {
      responsive: {
        mobile: {
          customStyle: {
            margin: '16px 0px 16px 0px',
            padding: '0px 0px 0px 0px',
            alignItems: 'start',
            background: '#fff',
            justifyContent: 'center',
          },
        },
        desktop: {
          customStyle: {
            margin: '16px 0px 16px 0px',
            padding: '0px 0px 0px 0px',
            alignItems: 'start',
            background: '#fff',
            justifyContent: 'center',
          },
        },
      },
      customStyle: {
        margin: '16px 0px 16px 0px',
        padding: '0px 0px 0px 0px',
        alignItems: 'start',
        background: '#fff',
        justifyContent: 'center',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'n8Usd8US6n',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  iGBWeg3jtQ: {
    type: { resolvedName: 'CraftParagraph' },
    nodes: [],
    props: {
      content: '內容創作者XXXX\n自我介紹簡述文字放置區塊',
      children: [],
      responsive: {
        desktop: {
          content: '內容創作者XXXX\n自我介紹簡述文字放置區塊',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            padding: '8px 0px 0px 0px',
            fontSize: 16,
            textAlign: 'center',
            fontWeight: 'normal',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        padding: '8px 0px 0px 0px',
        fontSize: 16,
        textAlign: 'center',
        fontWeight: 'normal',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '33X03hvb_L',
    isCanvas: false,
    displayName: '段落',
    linkedNodes: {},
  },
  kqVKXRXJEO: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['ImkQ5l_1MO', 'sMPx35ANUn'],
    props: {
      className: 'info-card',
      horizontal: true,
      responsive: {
        mobile: {
          className: 'info-card',
          horizontal: true,
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '8px 40px 8px 40px',
            alignItems: 'center',
            background: '#fff',
            justifyContent: 'start',
          },
        },
        desktop: {
          className: 'info-card',
          horizontal: true,
          customStyle: {
            margin: '12px 0px 0px 0px',
            padding: '16px 40px 16px 40px',
            alignItems: 'center',
            background: '#fff',
            justifyContent: 'start',
          },
        },
      },
      customStyle: {
        margin: '12px 0px 0px 0px',
        padding: '16px 40px 16px 40px',
        alignItems: 'center',
        background: '#fff',
        justifyContent: 'start',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'wV7BNTlojc',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  n8Usd8US6n: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['e4mEe3yShu', 'rNCFA2NeEY'],
    props: {
      className: 'info-card list-layout',
      horizontal: true,
      responsive: {
        desktop: {
          className: 'info-card list-layout',
          horizontal: true,
          customStyle: {
            margin: '12px 0px 0px 0px',
            padding: '16px 24px 16px 24px',
            alignItems: 'center',
            background: '#fff',
          },
        },
      },
      customStyle: {
        margin: '12px 0px 0px 0px',
        padding: '16px 24px 16px 24px',
        alignItems: 'center',
        background: '#fff',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'wV7BNTlojc',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  rNCFA2NeEY: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['33tWnxTRZE'],
    props: {
      className: '',
      responsive: {
        mobile: {
          className: '',
          customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: '#fff' },
        },
      },
      customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: '#fff' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'n8Usd8US6n',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  sMPx35ANUn: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['3tOLTpWI-V'],
    props: {
      responsive: {
        mobile: {
          customStyle: {
            margin: '16px 0px 16px 0px',
            padding: '0px 0px 0px 0px',
            alignItems: 'start',
            background: '#fff',
            justifyContent: 'center',
          },
        },
      },
      customStyle: {
        margin: '16px 0px 16px 0px',
        padding: '0px 0px 0px 0px',
        alignItems: 'start',
        background: '#fff',
        justifyContent: 'center',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'kqVKXRXJEO',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  tc24yklFH7: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '項目標題名稱',
      children: [],
      responsive: {
        desktop: {
          title: '項目標題名稱',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            fontSize: 18,
            textAlign: 'left',
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        fontSize: 18,
        textAlign: 'left',
        fontWeight: 'bold',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'DlsC29HXC1',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  uWLUFjySF_: {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 400,
      children: [],
      className: 'avatar',
      responsive: {
        desktop: {
          width: 400,
          className: 'avatar',
          customStyle: {
            width: '126px',
            height: '126px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/4c9714d0-40dc-4bb5-88c5-08a0062448d1)',
          },
        },
      },
      customStyle: {
        width: '126px',
        height: '126px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/4c9714d0-40dc-4bb5-88c5-08a0062448d1)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '33X03hvb_L',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  ugOFBDVO5F: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['O-Y2DSlwB3'],
    props: {
      className: '',
      responsive: {
        mobile: {
          className: '',
          customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: '#fff' },
        },
      },
      customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: '#fff' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'R4mhx0ef8w',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  wV7BNTlojc: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['Qq6IYoFZly', 'kqVKXRXJEO', 'n8Usd8US6n', 'R4mhx0ef8w', 'Iit-mDGi28', 'UWAO_R2_Yc'],
    props: {
      responsive: {
        mobile: { customStyle: { margin: '0px 0px 0px 0px', padding: '10px 16px 10px 16px', background: 'unset' } },
        tablet: { customStyle: { margin: '0px 0px 0px 0px', padding: '10px 100px 10px 100px', background: 'unset' } },
        desktop: { customStyle: { margin: '0px 0px 0px 0px', padding: '20px 400px 0px 400px', background: 'unset' } },
      },
      customStyle: { margin: '0px 0px 0px 0px', padding: '20px 400px 0px 400px', background: 'unset' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'HekVEZhI_j',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
}

export const templateC = {
  ROOT: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['HekVEZhI_j'],
    props: {
      responsive: { desktop: { customStyle: { padding: '0px 0px 0px 0px' } } },
      customStyle: { padding: '0px 0px 0px 0px' },
    },
    custom: { button: { label: 'deleteBlock' }, editing: true },
    hidden: false,
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  '-5UsLTKUd7': {
    type: { resolvedName: 'CraftSection' },
    nodes: ['HVV_Ql90WY', 'MppzSoPamF'],
    props: {
      link: '',
      openTab: true,
      className: 'info-card',
      responsive: {
        mobile: {
          link: '/programs/104da8fc-97a4-478d-a643-c2a3708379d8',
          openTab: true,
          className: 'info-card',
          customStyle: {
            margin: '12px 0px 0px 0px',
            padding: 'ㄢpx 0px 0px 0px',
            alignItems: 'center',
            background: '#fff',
            justifyContent: 'center',
          },
        },
        desktop: {
          link: '',
          openTab: true,
          className: 'info-card',
          customStyle: {
            margin: '12px 0px 0px 0px',
            padding: 'ㄢpx 0px 0px 0px',
            alignItems: 'center',
            background: '#fff',
            justifyContent: 'center',
          },
        },
      },
      customStyle: {
        margin: '12px 0px 0px 0px',
        padding: 'ㄢpx 0px 0px 0px',
        alignItems: 'center',
        background: '#fff',
        justifyContent: 'center',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'n8sRpAW3XM',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  '6LS1VXpPdN': {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '描述文字放置描述文字放置',
      children: [],
      responsive: {
        desktop: {
          title: '描述文字放置描述文字放置',
          customStyle: {
            color: '#9B9B9B',
            margin: '0px 0px 0px 0px',
            fontSize: 14,
            textAlign: 'left',
            fontWeight: 'normal',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#9B9B9B',
        margin: '0px 0px 0px 0px',
        fontSize: 14,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'gGMiB_TaYV',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  '9hvd32deAM': {
    type: { resolvedName: 'CraftSection' },
    nodes: ['bGVcQSo79L', 'TaDLuq8a2N', 'ENTtht4Xq_'],
    props: {
      className: 'info-card',
      responsive: {
        desktop: {
          className: 'info-card',
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '32px 24px 32px 24px',
            alignItems: 'center',
            background: '#fff',
          },
        },
      },
      customStyle: {
        margin: '0px 0px 0px 0px',
        padding: '32px 24px 32px 24px',
        alignItems: 'center',
        background: '#fff',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'oaKS-SXR_7',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  BlIhnoCreM: {
    type: { resolvedName: 'CraftButton' },
    nodes: [],
    props: {
      link: '',
      size: 'lg',
      block: true,
      title: '馬上查看',
      variant: 'solid',
      children: [],
      openNewTab: false,
      responsive: {
        desktop: {
          link: '',
          size: 'lg',
          block: true,
          title: '馬上查看',
          variant: 'solid',
          openNewTab: false,
          customStyle: { color: '#fff', margin: '12px 0px 0px 0px', backgroundColor: '#585858' },
        },
      },
      customStyle: { color: '#fff', margin: '12px 0px 0px 0px', backgroundColor: '#585858' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'oaKS-SXR_7',
    isCanvas: false,
    displayName: '按鈕',
    linkedNodes: {},
  },
  CyWdIQElWF: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['ljIHPAlGr3'],
    props: {
      responsive: {
        mobile: { customStyle: { padding: '0px 0px 20px 0px', backgroundColor: '#f8f8f8' } },
        desktop: { customStyle: { padding: '20px 0px 20px 0px', backgroundColor: '#f8f8f8' } },
      },
      customStyle: { padding: '20px 0px 20px 0px', backgroundColor: '#f8f8f8' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'HekVEZhI_j',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  ENTtht4Xq_: {
    type: { resolvedName: 'CraftParagraph' },
    nodes: [],
    props: {
      content: '內容創作者XXXX\n自我介紹簡述文字放置區塊',
      children: [],
      responsive: {
        desktop: {
          content: '內容創作者XXXX\n自我介紹簡述文字放置區塊',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            padding: '8px 0px 0px 0px',
            fontSize: 16,
            textAlign: 'center',
            fontWeight: 'normal',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        padding: '8px 0px 0px 0px',
        fontSize: 16,
        textAlign: 'center',
        fontWeight: 'normal',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '9hvd32deAM',
    isCanvas: false,
    displayName: '段落',
    linkedNodes: {},
  },
  H5Yob_fdoZ: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['XeoFUCCb1R'],
    props: {
      className: '',
      responsive: {
        mobile: {
          className: '',
          customStyle: { margin: '0px 20px 0px 0px', padding: '0px 0px 0px 0px', background: '#fff' },
        },
      },
      customStyle: { margin: '0px 20px 0px 0px', padding: '0px 0px 0px 0px', background: '#fff' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'Z-Klo1DPBg',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  HVV_Ql90WY: {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 400,
      children: [],
      className: 'card-img',
      responsive: {
        mobile: {
          width: 400,
          className: 'card-img',
          customStyle: {
            width: '100%',
            height: '180px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/92bdba0c-9abd-489e-8269-60ee8618e66f)',
          },
        },
        tablet: {
          width: 400,
          className: 'card-img',
          customStyle: {
            width: '100%',
            height: '280px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/92bdba0c-9abd-489e-8269-60ee8618e66f)',
          },
        },
        desktop: {
          width: 400,
          className: 'card-img',
          customStyle: {
            width: '100%',
            height: '380px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/92bdba0c-9abd-489e-8269-60ee8618e66f)',
          },
        },
      },
      customStyle: {
        width: '100%',
        height: '180px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/92bdba0c-9abd-489e-8269-60ee8618e66f)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '-5UsLTKUd7',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  HekVEZhI_j: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['CyWdIQElWF'],
    props: {
      responsive: {
        mobile: { customStyle: { padding: '0px 0px 20px 0px', backgroundColor: '#f8f8f8' } },
        desktop: { customStyle: { padding: '0px 0px 20px 0px', backgroundColor: '#f8f8f8' } },
      },
      customStyle: { padding: '0px 0px 20px 0px', backgroundColor: '#f8f8f8' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  'LIrsrBz6-d': {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '立即領取專屬優惠',
      children: [],
      responsive: {
        desktop: {
          title: '立即領取專屬優惠',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            fontSize: 18,
            textAlign: 'left',
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        fontSize: 18,
        textAlign: 'left',
        fontWeight: 'bold',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'wtBjdYH41I',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  MppzSoPamF: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '項目標題名稱',
      children: [],
      responsive: {
        desktop: {
          title: '項目標題名稱',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            padding: '20px 20px 20px 20px',
            fontSize: 18,
            textAlign: 'center',
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        padding: '20px 20px 20px 20px',
        fontSize: 18,
        textAlign: 'center',
        fontWeight: 'bold',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '-5UsLTKUd7',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  TaDLuq8a2N: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '名稱',
      children: [],
      responsive: {
        desktop: {
          title: '名稱',
          customStyle: {
            color: '#585858',
            margin: '20px 4px 0px 4px',
            fontSize: 24,
            textAlign: 'center',
            fontWeight: 'bold',
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '20px 4px 0px 4px',
        fontSize: 24,
        textAlign: 'center',
        fontWeight: 'bold',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '9hvd32deAM',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  XeoFUCCb1R: {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 400,
      children: [],
      responsive: {
        tablet: {
          width: 400,
          customStyle: {
            width: '32px',
            height: '36px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/cb17cc05-118b-4970-b51e-60730430f56f)',
          },
        },
      },
      customStyle: {
        width: '32px',
        height: '36px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/cb17cc05-118b-4970-b51e-60730430f56f)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'H5Yob_fdoZ',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  'Z-Klo1DPBg': {
    type: { resolvedName: 'CraftSection' },
    nodes: ['H5Yob_fdoZ', 'wtBjdYH41I'],
    props: {
      className: 'info-card',
      horizontal: true,
      responsive: {
        mobile: {
          className: 'info-card',
          horizontal: true,
          customStyle: {
            margin: '0px 0px 0px 0px',
            padding: '8px 40px 8px 40px',
            alignItems: 'center',
            background: '#fff',
            justifyContent: 'start',
          },
        },
        tablet: {
          className: 'info-card',
          horizontal: true,
          customStyle: {
            margin: 'px',
            padding: '16px 40px 16px 40px',
            alignItems: 'center',
            background: '#fff',
            justifyContent: 'start',
          },
        },
        desktop: {
          className: 'info-card',
          horizontal: true,
          customStyle: {
            margin: '12px 0px 0px 0px',
            padding: '16px 40px 16px 40px',
            alignItems: 'center',
            background: '#fff',
            justifyContent: 'start',
          },
        },
      },
      customStyle: {
        margin: '12px 0px 0px 0px',
        padding: '16px 40px 16px 40px',
        alignItems: 'center',
        background: '#fff',
        justifyContent: 'start',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'n8sRpAW3XM',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  bGVcQSo79L: {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 400,
      children: [],
      className: 'avatar',
      responsive: {
        desktop: {
          width: 400,
          className: 'avatar',
          customStyle: {
            width: '126px',
            height: '126px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/4c9714d0-40dc-4bb5-88c5-08a0062448d1)',
          },
        },
      },
      customStyle: {
        width: '126px',
        height: '126px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/4c9714d0-40dc-4bb5-88c5-08a0062448d1)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: '9hvd32deAM',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  cPFRrb0PZf: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['pTP5y1Puyt'],
    props: {
      className: '',
      responsive: {
        mobile: {
          className: '',
          customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: '#fff' },
        },
      },
      customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: '#fff' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'jHDZNpelIA',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  gGMiB_TaYV: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['mgg_v1hA7v', '6LS1VXpPdN'],
    props: {
      responsive: {
        mobile: {
          customStyle: {
            margin: '16px 0px 16px 0px',
            padding: '0px 0px 0px 0px',
            alignItems: 'start',
            background: '#fff',
            justifyContent: 'center',
          },
        },
        desktop: {
          customStyle: {
            margin: '16px 0px 16px 0px',
            padding: '0px 0px 0px 0px',
            alignItems: 'start',
            background: '#fff',
            justifyContent: 'center',
          },
        },
      },
      customStyle: {
        margin: '16px 0px 16px 0px',
        padding: '0px 0px 0px 0px',
        alignItems: 'start',
        background: '#fff',
        justifyContent: 'center',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'mTj0wb2c7K',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  hIRtUH07yY: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['tDzqLrUhxY'],
    props: {
      className: '',
      responsive: {
        mobile: {
          className: '',
          customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: '#fff' },
        },
      },
      customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: '#fff' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'mTj0wb2c7K',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  jHDZNpelIA: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['tiKnTUFNr3', 'cPFRrb0PZf'],
    props: {
      className: 'info-card list-layout',
      horizontal: true,
      responsive: {
        desktop: {
          className: 'info-card list-layout',
          horizontal: true,
          customStyle: {
            margin: '12px 0px 0px 0px',
            padding: '16px 24px 16px 24px',
            alignItems: 'center',
            background: '#fff',
          },
        },
      },
      customStyle: {
        margin: '12px 0px 0px 0px',
        padding: '16px 24px 16px 24px',
        alignItems: 'center',
        background: '#fff',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'n8sRpAW3XM',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  jW8ff2G0tQ: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['nel_G-Q4Ts'],
    props: {
      responsive: {
        mobile: { customStyle: { margin: '12px 0px 0px 0px', padding: '0px 0px 0px 0px', background: 'unset' } },
        desktop: { customStyle: { margin: 'px 0px 12px 0px', padding: '0px 0px 0px 0px', background: 'unset' } },
      },
      customStyle: { margin: 'px 0px 12px 0px', padding: '0px 0px 0px 0px', background: 'unset' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'n8sRpAW3XM',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  ljIHPAlGr3: {
    type: { resolvedName: 'CraftLayout' },
    nodes: ['oaKS-SXR_7', 'n8sRpAW3XM'],
    props: {
      ratios: [1],
      responsive: {
        mobile: { ratios: [1], customStyle: { gap: 0, padding: '0px 16px 0px 16px' } },
        tablet: { ratios: [1], customStyle: { gap: 0, padding: '0px 50px 0px 50px' } },
        desktop: { ratios: [3, 7], customStyle: { gap: 40, padding: '0px 240px 0px 240px' } },
      },
      customStyle: { gap: 0, padding: '0px 16px 0px 16px' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'CyWdIQElWF',
    isCanvas: true,
    displayName: '佈局',
    linkedNodes: {},
  },
  mTj0wb2c7K: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['gGMiB_TaYV', 'hIRtUH07yY'],
    props: {
      className: 'info-card list-layout',
      horizontal: true,
      responsive: {
        desktop: {
          className: 'info-card list-layout',
          horizontal: true,
          customStyle: {
            margin: '12px 0px 0px 0px',
            padding: '16px 24px 16px 24px',
            alignItems: 'center',
            background: '#fff',
          },
        },
      },
      customStyle: {
        margin: '12px 0px 0px 0px',
        padding: '16px 24px 16px 24px',
        alignItems: 'center',
        background: '#fff',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'n8sRpAW3XM',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  mgg_v1hA7v: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '項目標題名稱',
      children: [],
      responsive: {
        desktop: {
          title: '項目標題名稱',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            fontSize: 18,
            textAlign: 'left',
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        fontSize: 18,
        textAlign: 'left',
        fontWeight: 'bold',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'gGMiB_TaYV',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  n8sRpAW3XM: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['jW8ff2G0tQ', 'Z-Klo1DPBg', 'mTj0wb2c7K', 'jHDZNpelIA', '-5UsLTKUd7'],
    props: {
      responsive: {
        mobile: { customStyle: { margin: '0px 0px 0px 0px', padding: '10px 0px 10px 0px', background: 'unset' } },
        tablet: { customStyle: { margin: '0px 0px 0px 0px', padding: '10px 100px 10px 100px', background: 'unset' } },
        desktop: { customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: 'unset' } },
      },
      customStyle: { margin: '0px 0px 0px 0px', padding: '10px 0px 10px 0px', background: 'unset' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'ljIHPAlGr3',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  'nel_G-Q4Ts': {
    type: { resolvedName: 'CraftActivityCollection' },
    nodes: [],
    props: {
      layout: { gap: 1, columns: 1 },
      source: { from: 'custom', limit: 1, idList: ['e7191df3-1c6f-448d-ae11-a3e4d8997af0'] },
      variant: 'card',
      children: [],
      responsive: {
        desktop: {
          layout: { gap: 1, columns: 1 },
          source: { from: 'custom', limit: 1, idList: ['e7191df3-1c6f-448d-ae11-a3e4d8997af0'] },
          variant: 'card',
        },
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'jW8ff2G0tQ',
    isCanvas: false,
    displayName: '活動',
    linkedNodes: {},
  },
  'oaKS-SXR_7': {
    type: { resolvedName: 'CraftSection' },
    nodes: ['9hvd32deAM', 'BlIhnoCreM'],
    props: {
      responsive: {
        mobile: { customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: 'unset' } },
        tablet: { customStyle: { margin: '0 0 5px 0', padding: '0px 100px 0px 100px', background: 'unset' } },
        desktop: { customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: 'unset' } },
      },
      customStyle: { margin: '0px 0px 0px 0px', padding: '0px 0px 0px 0px', background: 'unset' },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'ljIHPAlGr3',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  pTP5y1Puyt: {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 400,
      children: [],
      responsive: {
        desktop: {
          width: 400,
          customStyle: {
            width: '20px',
            height: '20px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/b64228c2-6957-4137-a84b-80444ce51c98)',
          },
        },
      },
      customStyle: {
        width: '20px',
        height: '20px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/b64228c2-6957-4137-a84b-80444ce51c98)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'cPFRrb0PZf',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  rVxF0wZRf5: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      title: '項目標題名稱',
      children: [],
      responsive: {
        desktop: {
          title: '項目標題名稱',
          customStyle: {
            color: '#585858',
            margin: '0px 0px 0px 0px',
            fontSize: 18,
            textAlign: 'left',
            fontWeight: 'bold',
            lineHeight: 1.5,
          },
        },
      },
      customStyle: {
        color: '#585858',
        margin: '0px 0px 0px 0px',
        fontSize: 18,
        textAlign: 'left',
        fontWeight: 'bold',
        lineHeight: 1.5,
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'tiKnTUFNr3',
    isCanvas: false,
    displayName: '標題',
    linkedNodes: {},
  },
  tDzqLrUhxY: {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      width: 400,
      children: [],
      className: 'list-img',
      responsive: {
        desktop: {
          width: 400,
          className: 'list-img',
          customStyle: {
            width: '64px',
            height: '64px',
            backgroundImage:
              'url(https://static-dev.kolable.com/images/demo/craft/17823d0c-e4da-4b7c-ad4b-6ab9f1bc081a)',
          },
        },
      },
      customStyle: {
        width: '64px',
        height: '64px',
        backgroundImage: 'url(https://static-dev.kolable.com/images/demo/craft/17823d0c-e4da-4b7c-ad4b-6ab9f1bc081a)',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'hIRtUH07yY',
    isCanvas: false,
    displayName: '圖片',
    linkedNodes: {},
  },
  tiKnTUFNr3: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['rVxF0wZRf5'],
    props: {
      responsive: {
        mobile: {
          customStyle: {
            margin: '16px 0px 16px 0px',
            padding: '0px 0px 0px 0px',
            alignItems: 'start',
            background: '#fff',
            justifyContent: 'center',
          },
        },
      },
      customStyle: {
        margin: '16px 0px 16px 0px',
        padding: '0px 0px 0px 0px',
        alignItems: 'start',
        background: '#fff',
        justifyContent: 'center',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'jHDZNpelIA',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
  wtBjdYH41I: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['LIrsrBz6-d'],
    props: {
      responsive: {
        mobile: {
          customStyle: {
            margin: '16px 0px 16px 0px',
            padding: '0px 0px 0px 0px',
            alignItems: 'start',
            background: '#fff',
            justifyContent: 'center',
          },
        },
      },
      customStyle: {
        margin: '16px 0px 16px 0px',
        padding: '0px 0px 0px 0px',
        alignItems: 'start',
        background: '#fff',
        justifyContent: 'center',
      },
    },
    custom: { editing: false },
    hidden: false,
    parent: 'Z-Klo1DPBg',
    isCanvas: true,
    displayName: '區塊',
    linkedNodes: {},
  },
}
