export { ReactComponent as PlusIcon } from './plus.svg'
export { ReactComponent as PageIcon } from './page.svg'
export { ReactComponent as BrushIcon } from './paintbrush.svg'
export { ReactComponent as TrashOIcon } from './trash-o.svg'
export { ReactComponent as LockIcon } from './lock.svg'
export { ReactComponent as DiscountIcon } from './discount.svg'
