export const templateDefault = {
  ROOT: {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: [],
    props: {
      margin: {
        mb: '0',
        ml: '0',
        mr: '0',
        mt: '0',
      },
      padding: {
        pb: 10,
        pl: 0,
        pr: 0,
        pt: 0,
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
}

export const templateA = {
  ROOT: {
    type: { resolvedName: 'CraftSection' },
    nodes: [
      'AN590c6qsa',
      'D-F42wYLar',
      'WBU-CKpIwk',
      'xt2ekQJFhT',
      'RydfSkPn0x',
      '9zEySw6IsN',
      'xh0VGyR3UK',
      'ccPESSbyNE',
      'zvFuLfkDoN',
    ],
    props: { margin: { mb: '0', ml: '0', mr: '0', mt: '0' }, padding: { pb: 1, pl: '0', pr: '0', pt: '0' } },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  '-udbODIgwN': {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      color: '#585858',
      margin: { mb: '40' },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '線上課程',
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'WBU-CKpIwk',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  '1-5QQ92_pD': {
    type: { resolvedName: 'CraftCarousel' },
    nodes: ['C_cLZQOQi8', 'pVPMkyHTpi', '_HjjgF0Cju'],
    props: {
      id: 'CraftCarousel',
      mobile: {
        margin: { mb: '0', ml: '16', mr: '16', mt: '0' },
        slidesToShow: 1,
        swipeToSlide: true,
        slidesToScroll: 1,
      },
      desktop: {
        margin: { mb: '0', ml: '20', mr: '20', mt: '0' },
        slidesToShow: 3,
        swipeToSlide: true,
        slidesToScroll: 1,
      },
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'ccPESSbyNE',
    isCanvas: true,
    displayName: 'CraftCarousel',
    linkedNodes: {},
  },
  '3FmwrkP10S': {
    type: { resolvedName: 'CraftCollapse' },
    nodes: [],
    props: {
      id: 'CraftCollapse2',
      title: '課程可以看幾次？',
      variant: 'backgroundColor',
      paragraph:
        '網站的「線上課程」都可以隨時隨地透過電腦、手機、平板觀看購買後的課程影片，沒有時間和地點的限制！ 都可以隨時隨地透過電腦手機平板觀看購買後的課程影片沒有時間和地點的限制',
      cardMargin: { mb: '0', ml: '0', mr: '0', mt: -15 },
      solidColor: '#ffffff32',
      titleStyle: {
        color: '#ffffff',
        margin: { mb: '0', ml: '0', mr: '0', mt: '0' },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: { pb: 20, pl: 20, pr: 20, pt: 20 },
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#ffffff',
        margin: { mb: '0', ml: '0', mr: '0', mt: 20 },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
      },
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'OMIH3jlA6O',
    isCanvas: true,
    displayName: 'CraftCollapse',
    linkedNodes: {},
  },
  '5XRb8t0YDD': {
    type: { resolvedName: 'CraftInstructor' },
    nodes: [],
    props: { appId: 'demo' },
    custom: {},
    hidden: false,
    parent: '9zEySw6IsN',
    isCanvas: false,
    displayName: 'CraftInstructor',
    linkedNodes: {},
  },
  '6XNFOXfPVW': {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      color: '#585858',
      margin: { mb: '25' },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '推薦評價',
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'ccPESSbyNE',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  '7-6PQSEAG0': {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      color: '#585858',
      margin: { mb: '25' },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '提供完善的服務',
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'D-F42wYLar',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  '9zEySw6IsN': {
    type: { resolvedName: 'CraftSection' },
    nodes: ['C0ar-CG-ob', '5XRb8t0YDD'],
    props: {
      id: 'CraftSection',
      margin: { mb: 5, ml: '0', mr: '0', mt: '0' },
      padding: { pb: 64, pl: 120, pr: 120, pt: 64 },
      backgroundType: 'none',
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  AN590c6qsa: {
    type: { resolvedName: 'CraftCarousel' },
    nodes: [],
    props: {
      type: 'normal',
      covers: [
        {
          link: '/programs',
          title: '換個方式說溝通更有效',
          paragraph:
            '生命的目的是盡可能多地成為你自己，將你天生的才能和能力與你生活經驗中的智慧結合起來，並將它們與你內在的精神融合在一起，然後把自己作為禮物送回世界。',
          openNewTab: false,
          mobileCoverUrl: 'https://static.kolable.com/images/demo/cover-01-m.png',
          desktopCoverUrl: 'https://static.kolable.com/images/demo/cover-01.png',
        },
        {
          link: '',
          title: '',
          paragraph: '',
          openNewTab: false,
          mobileCoverUrl: 'https://static.kolable.com/images/demo/cover-02-m.jpg',
          desktopCoverUrl: 'https://static.kolable.com/images/demo/cover-02.jpg',
        },
      ],
      titleStyle: {
        color: '#ffffff',
        margin: { mb: '0', ml: '0', mr: '0', mt: '0' },
        fontSize: 26,
        textAlign: 'center',
        fontWeight: 'bold',
      },
      paragraphStyle: {
        color: '#ffffff',
        margin: { mb: '0', ml: '0', mr: '0', mt: '0' },
        fontSize: 16,
        textAlign: 'center',
        fontWeight: 'normal',
        lineHeight: 1.5,
      },
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'CraftCarousel',
    linkedNodes: {},
  },
  AtE_Tn_6G3: {
    type: { resolvedName: 'CraftCard' },
    nodes: [],
    props: {
      type: 'featureWithParagraph',
      title: '特色標題',
      variant: 'backgroundColor',
      imageUrl: 'https://static.kolable.com/images/demo/home/icon-thumb-blue.svg',
      imageType: 'image',
      paragraph: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
      cardMargin: { mb: '0', ml: '0', mr: '0', mt: '0' },
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: { mb: 8, ml: '0', mr: '0', mt: '0' },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: { pb: 32, pl: 32, pr: 32, pt: 32 },
      imageMargin: { mb: 16, ml: '0', mr: '0', mt: '0' },
      imagePadding: { pb: '0', pl: '0', pr: '0', pt: '0' },
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#585858',
        margin: { mb: '0', ml: '0', mr: 20, mt: '0' },
        fontSize: 14,
        textAlign: 'left',
        fontWeight: 'lighter',
        lineHeight: 1.57,
      },
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'rW2v9GmigE',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  'C0ar-CG-ob': {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      color: '#585858',
      margin: { mb: '25' },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '專業師資',
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: '9zEySw6IsN',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  C_cLZQOQi8: {
    type: { resolvedName: 'CraftCard' },
    nodes: [],
    props: {
      type: 'referrer',
      title: '公務員',
      variant: 'backgroundColor',
      imageUrl: '',
      imageType: 'none',
      paragraph:
        '我原是從事公務人員的相關工作，在職訓局上過一期的網頁課，就開始從事網頁工作，覺得自己有很多不足之處，但又不知從何學起，自行看書也覺所學有限，學習網頁資源國外相對較多，但無奈英文不好，爬文的很累。好在看到這門課程，從基礎靜態網頁到進階的互動網頁，都有詳細又美觀的示範案例，很推薦所有對網頁有興趣的朋友。',
      avatarName: '阿公',
      avatarType: 'image',
      cardMargin: {},
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: { mb: '12', mt: '0' },
        fontSize: 20,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: { pb: '40', pl: '40', pr: '40', pt: '40' },
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#9b9b9b',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: '1-5QQ92_pD',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  'D-F42wYLar': {
    type: { resolvedName: 'CraftSection' },
    nodes: ['7-6PQSEAG0', 'Y-TTBUArYh'],
    props: {
      id: 'CraftSection',
      margin: { mb: 5, ml: '0', mr: '0', mt: '0' },
      padding: { pb: 40, pl: '0', pr: '0', pt: 80 },
      backgroundType: 'none',
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  DfHQujh90U: {
    type: { resolvedName: 'CraftCard' },
    nodes: [],
    props: {
      type: 'featureWithParagraph',
      title: '特色標題',
      variant: 'backgroundColor',
      imageUrl: 'https://static.kolable.com/images/demo/home/icon-thumb-blue.svg',
      imageType: 'image',
      paragraph: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
      cardMargin: { mb: '0', ml: '0', mr: '0', mt: '0' },
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: { mb: 8, ml: '0', mr: '0', mt: '0' },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: { pb: 32, pl: 32, pr: 32, pt: 32 },
      imageMargin: { mb: 16, ml: '0', mr: '0', mt: '0' },
      imagePadding: { pb: '0', pl: '0', pr: '0', pt: '0' },
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#585858',
        margin: { mb: '0', ml: '0', mr: 20, mt: '0' },
        fontSize: 14,
        textAlign: 'left',
        fontWeight: 'lighter',
        lineHeight: 1.57,
      },
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'rW2v9GmigE',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  E3wHkNuNAF: {
    type: { resolvedName: 'CraftParagraph' },
    nodes: [],
    props: {
      color: '#585858',
      margin: {},
      fontSize: 16,
      textAlign: 'left',
      fontWeight: 'normal',
      lineHeight: 1.69,
      paragraphContent:
        '但是什麼時候該理想，什麼時候該現實，什麼時候該堅持，什麼時候該妥協，又是一門藝術了，而這中間的拿捏，也是「初階的管理人才」與「進階的管理人才」之間的差別吧！但是什麼時候該理想，什麼時候該現實，什麼時候該堅持，什麼時候該妥協，又是一門藝術了，而這中間的拿捏，也是「初階的管理人才」與「進階的管理人才」之間的差別吧！',
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'z61MeqQqwu',
    isCanvas: false,
    displayName: 'CraftParagraph',
    linkedNodes: {},
  },
  'FJvbo0m-CW': {
    type: { resolvedName: 'CraftStatistics' },
    nodes: [],
    props: {
      type: 'image',
      title: {
        color: '#4C5B8F',
        margin: { mb: '16' },
        fontSize: 40,
        textAlign: 'center',
        fontWeight: 'normal',
        titleContent: '814+',
      },
      margin: {},
      padding: { pb: '10', pt: '10' },
      coverUrl: 'https://static.kolable.com/images/demo/home/icon-savetime.svg',
      paragraph: {
        color: '#585858',
        margin: {},
        fontSize: 14,
        textAlign: 'center',
        fontWeight: 'lighter',
        paragraphContent: '覺得超有效',
      },
    },
    custom: {},
    hidden: false,
    parent: 'Y-TTBUArYh',
    isCanvas: false,
    displayName: 'CraftStatistics',
    linkedNodes: {},
  },
  Hlokdj0WsE: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      color: '#585858',
      margin: { mb: 40, ml: '0', mr: '0', mt: '0' },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '三大特色',
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'RydfSkPn0x',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  I2pPTe9ShY: {
    type: { resolvedName: 'CraftLayout' },
    nodes: ['pG7c03oC0o', 'kyMph99CT5'],
    props: {
      id: 'CraftLayout',
      mobile: { margin: { ml: '20', mr: '20' }, columnRatio: [12], columnAmount: 1, displayAmount: 2 },
      desktop: { margin: { ml: '200', mr: '200' }, columnRatio: [3, 2], columnAmount: 2, displayAmount: 2 },
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'xh0VGyR3UK',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  IvZQ3sqOIj: {
    type: { resolvedName: 'CraftStatistics' },
    nodes: [],
    props: {
      type: 'image',
      title: {
        color: '#4C5B8F',
        margin: { mb: '16' },
        fontSize: 40,
        textAlign: 'center',
        fontWeight: 'normal',
        titleContent: '353+',
      },
      margin: {},
      padding: { pb: '10', pt: '10' },
      coverUrl: 'https://static.kolable.com/images/demo/home/icon-savetime.svg',
      paragraph: {
        color: '#585858',
        margin: {},
        fontSize: 14,
        textAlign: 'center',
        fontWeight: 'lighter',
        paragraphContent: '覺得超有效',
      },
    },
    custom: {},
    hidden: false,
    parent: 'Y-TTBUArYh',
    isCanvas: false,
    displayName: 'CraftStatistics',
    linkedNodes: {},
  },
  KizdarCnYR: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      color: '#585858',
      margin: { mb: '24' },
      fontSize: 20,
      textAlign: 'left',
      fontWeight: 'bold',
      titleContent: '屹立不搖的組織都有相同的模式',
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'z61MeqQqwu',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  MHpM0jL7VP: {
    type: { resolvedName: 'CraftImage' },
    nodes: [],
    props: {
      type: 'image',
      width: '100%',
      margin: {},
      padding: {},
      coverUrl: 'https://static.kolable.com/images/demo/home/feature-img2.jpg',
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'WTOZ7XwBcE',
    isCanvas: false,
    displayName: 'CraftImage',
    linkedNodes: {},
  },
  NtxPBJVrkH: {
    type: { resolvedName: 'CraftLayout' },
    nodes: ['Vyg85h9FYN'],
    props: {
      id: 'CraftLayout',
      mobile: { margin: { mb: '20', ml: '16', mr: '16' }, columnRatio: [12], columnAmount: 1, displayAmount: 3 },
      desktop: {
        margin: { mb: '20', ml: '120', mr: '120' },
        columnRatio: [4, 4, 4],
        columnAmount: 3,
        displayAmount: 3,
      },
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'WBU-CKpIwk',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  OMIH3jlA6O: {
    type: { resolvedName: 'CraftLayout' },
    nodes: ['i8XIibir2U', '3FmwrkP10S', 'pJ0Kg_xMnU'],
    props: {
      id: 'CraftLayout',
      mobile: { margin: { mb: '0', ml: 20, mr: 20, mt: '0' }, columnRatio: [12], columnAmount: 1, displayAmount: 2 },
      desktop: { margin: { mb: '0', ml: 200, mr: 200, mt: '0' }, columnRatio: [12], columnAmount: 1, displayAmount: 3 },
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'zvFuLfkDoN',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  RydfSkPn0x: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['Hlokdj0WsE', 'rW2v9GmigE'],
    props: {
      id: 'CraftSection',
      margin: { mb: 5, ml: '0', mr: '0', mt: '0' },
      padding: { pb: 64, pl: '0', pr: '0', pt: 64 },
      backgroundType: 'none',
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  Ut3PNSjUUb: {
    type: { resolvedName: 'CraftStatistics' },
    nodes: [],
    props: {
      type: 'image',
      title: {
        color: '#4C5B8F',
        margin: { mb: '16' },
        fontSize: 40,
        textAlign: 'center',
        fontWeight: 'normal',
        titleContent: '666+',
      },
      margin: {},
      padding: { pb: '10', pt: '10' },
      coverUrl: 'https://static.kolable.com/images/demo/home/icon-thumb.svg',
      paragraph: {
        color: '#585858',
        margin: {},
        fontSize: 14,
        textAlign: 'center',
        fontWeight: 'lighter',
        paragraphContent: '覺得超省時間',
      },
    },
    custom: {},
    hidden: false,
    parent: 'Y-TTBUArYh',
    isCanvas: false,
    displayName: 'CraftStatistics',
    linkedNodes: {},
  },
  Vyg85h9FYN: {
    type: { resolvedName: 'CraftProgram' },
    nodes: [],
    props: {},
    custom: {},
    hidden: false,
    parent: 'NtxPBJVrkH',
    isCanvas: false,
    displayName: 'CraftProgram',
    linkedNodes: {},
  },
  'WBU-CKpIwk': {
    type: { resolvedName: 'CraftSection' },
    nodes: ['-udbODIgwN', 'NtxPBJVrkH', 'h3PXKv0k9R'],
    props: {
      id: 'CraftSection',
      margin: { mb: 1, ml: '0', mr: '0', mt: '0' },
      padding: { pb: 64, pl: '0', pr: '0', pt: 64 },
      backgroundType: 'none',
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  WCKPeALtPE: {
    type: { resolvedName: 'CraftStatistics' },
    nodes: [],
    props: {
      type: 'image',
      title: {
        color: '#4C5B8F',
        margin: { mb: '16' },
        fontSize: 40,
        textAlign: 'center',
        fontWeight: 'normal',
        titleContent: '999+',
      },
      margin: {},
      padding: { pb: '10', pt: '10' },
      coverUrl: 'https://static.kolable.com/images/demo/home/icon-thumb.svg',
      paragraph: {
        color: '#585858',
        margin: {},
        fontSize: 14,
        textAlign: 'center',
        fontWeight: 'lighter',
        paragraphContent: '覺得超省時間',
      },
    },
    custom: {},
    hidden: false,
    parent: 'Y-TTBUArYh',
    isCanvas: false,
    displayName: 'CraftStatistics',
    linkedNodes: {},
  },
  WTOZ7XwBcE: {
    type: { resolvedName: 'CraftLayout' },
    nodes: ['z61MeqQqwu', 'MHpM0jL7VP'],
    props: {
      id: 'CraftLayout',
      mobile: { margin: { ml: '15', mr: '15' }, columnRatio: [12], columnAmount: 1, displayAmount: 2 },
      desktop: { margin: { ml: '200', mr: '200' }, columnRatio: [6, 4], columnAmount: 2, displayAmount: 2 },
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'xt2ekQJFhT',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  XhlpkAeouR: {
    type: { resolvedName: 'CraftButton' },
    nodes: [],
    props: {
      link: '/programs',
      size: 'md',
      block: false,
      color: '#4C5B8F',
      title: '馬上查看 〉',
      variant: 'text',
      openNewTab: false,
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'h3PXKv0k9R',
    isCanvas: false,
    displayName: 'CraftButton',
    linkedNodes: {},
  },
  'Y-TTBUArYh': {
    type: { resolvedName: 'CraftLayout' },
    nodes: ['FJvbo0m-CW', 'WCKPeALtPE', 'IvZQ3sqOIj', 'Ut3PNSjUUb'],
    props: {
      id: 'CraftLayout',
      mobile: { margin: { mb: '0', ml: '0', mr: '0', mt: '0' }, columnRatio: [12], columnAmount: 1, displayAmount: 4 },
      desktop: {
        margin: { mb: '0', ml: '0', mr: '0', mt: '0' },
        columnRatio: [3, 3, 3, 3],
        columnAmount: 4,
        displayAmount: 4,
      },
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'D-F42wYLar',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  _HjjgF0Cju: {
    type: { resolvedName: 'CraftCard' },
    nodes: [],
    props: {
      type: 'referrer',
      title: '學生',
      variant: 'backgroundColor',
      imageUrl: '',
      imageType: 'none',
      paragraph:
        '前面程式的課程，經過老師由淺入深的講解和數個範例練習，重新幫我建構了網頁設計的觀念，讓我得以將以前那些片段的知識都串接起來並賦予意義，就好像建立了系統性的架構，瞬間有豁然開朗的感覺。',
      avatarName: '阿生',
      avatarType: 'image',
      cardMargin: {},
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: { mb: '12', mt: '0' },
        fontSize: 20,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: { pb: '40', pl: '40', pr: '40', pt: '40' },
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#9b9b9b',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: '1-5QQ92_pD',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  _tAodfFvu7: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      color: '#ffffff',
      margin: { mb: 40, ml: '0', mr: '0', mt: '0' },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '常見問題',
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'zvFuLfkDoN',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  bYgcKL5UAi: {
    type: { resolvedName: 'CraftCard' },
    nodes: [],
    props: {
      type: 'featureWithParagraph',
      title: '特色標題',
      variant: 'backgroundColor',
      imageUrl: 'https://static.kolable.com/images/demo/home/icon-thumb-blue.svg',
      imageType: 'image',
      paragraph: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
      cardMargin: { mb: '0', ml: '0', mr: '0', mt: '0' },
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: { mb: 8, ml: '0', mr: '0', mt: '0' },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: { pb: 32, pl: 32, pr: 32, pt: 32 },
      imageMargin: { mb: 16, ml: '0', mr: '0', mt: '0' },
      imagePadding: { pb: '0', pl: '0', pr: '0', pt: '0' },
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#585858',
        margin: { mb: '0', ml: '0', mr: 20, mt: '0' },
        fontSize: 14,
        textAlign: 'left',
        fontWeight: 'lighter',
        lineHeight: 1.57,
      },
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'rW2v9GmigE',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  ccPESSbyNE: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['6XNFOXfPVW', '1-5QQ92_pD'],
    props: {
      id: 'CraftSection',
      margin: { mb: 1, ml: '0', mr: '0', mt: '0' },
      padding: { pb: 64, pl: '0', pr: '0', pt: 64 },
      backgroundType: 'none',
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  h3PXKv0k9R: {
    type: 'div',
    nodes: ['XhlpkAeouR'],
    props: { style: { textAlign: 'center' } },
    custom: {},
    hidden: false,
    parent: 'WBU-CKpIwk',
    isCanvas: false,
    displayName: 'div',
    linkedNodes: {},
  },
  i8XIibir2U: {
    type: { resolvedName: 'CraftCollapse' },
    nodes: [],
    props: {
      id: 'CraftCollapse1',
      title: '什麼是線上課程? 請問在哪裡上課？上課時間？',
      variant: 'backgroundColor',
      paragraph:
        '網站的「線上課程」都可以隨時隨地透過電腦、手機、平板觀看購買後的課程影片，沒有時間和地點的限制！ 都可以隨時隨地透過電腦手機平板觀看購買後的課程影片沒有時間和地點的限制',
      cardMargin: { mb: '0', ml: '0', mr: '0', mt: '0' },
      solidColor: '#ffffff32',
      titleStyle: {
        color: '#ffffff',
        margin: { mb: '0', ml: '0', mr: '0', mt: '0' },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: { pb: 20, pl: 20, pr: 20, pt: 20 },
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#ffffff',
        margin: { mb: '0', ml: '0', mr: '0', mt: 20 },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
      },
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'OMIH3jlA6O',
    isCanvas: true,
    displayName: 'CraftCollapse',
    linkedNodes: {},
  },
  kyMph99CT5: {
    type: { resolvedName: 'CraftButton' },
    nodes: [],
    props: {
      link: '',
      size: 'lg',
      block: false,
      color: '#fff',
      title: '前往註冊',
      variant: 'outline',
      openNewTab: false,
      outlineColor: '#fff',
      backgroundType: 'none',
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'I2pPTe9ShY',
    isCanvas: false,
    displayName: 'CraftButton',
    linkedNodes: {},
  },
  pG7c03oC0o: {
    type: { resolvedName: 'CraftTitle' },
    nodes: [],
    props: {
      color: 'white',
      margin: { mb: '0', ml: '0', mr: '0', mt: '0' },
      fontSize: 28,
      textAlign: 'center',
      fontWeight: 'normal',
      titleContent: '還在等什麼？立即加入會員',
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'I2pPTe9ShY',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  pJ0Kg_xMnU: {
    type: { resolvedName: 'CraftCollapse' },
    nodes: [],
    props: {
      id: 'CraftCollapse3',
      title: '可以問老師問題嗎？',
      variant: 'backgroundColor',
      paragraph:
        '網站的「線上課程」都可以隨時隨地透過電腦、手機、平板觀看購買後的課程影片，沒有時間和地點的限制！ 都可以隨時隨地透過電腦手機平板觀看購買後的課程影片沒有時間和地點的限制',
      cardMargin: { mb: '0', ml: '0', mr: '0', mt: -15 },
      solidColor: '#ffffff32',
      titleStyle: {
        color: '#ffffff',
        margin: { mb: '0', ml: '0', mr: '0', mt: '0' },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: { pb: 20, pl: 20, pr: 20, pt: 20 },
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#ffffff',
        margin: { mb: '0', ml: '0', mr: '0', mt: 20 },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
      },
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'OMIH3jlA6O',
    isCanvas: true,
    displayName: 'CraftCollapse',
    linkedNodes: {},
  },
  pVPMkyHTpi: {
    type: { resolvedName: 'CraftCard' },
    nodes: [],
    props: {
      type: 'referrer',
      title: '行政助理',
      variant: 'backgroundColor',
      imageUrl: '',
      imageType: 'none',
      paragraph:
        '本身非本科畢業，對於設計的知識和技能都是靠零散的自學，但一直沒有融會貫通的感覺，經過老師由淺入深的講解和數個範例練習，重新幫我建構設計的觀念，很適合想踏入這個領遇卻不知道從何開始的人學習！',
      avatarName: '熙雯',
      avatarType: 'image',
      cardMargin: {},
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: { mb: '12', mt: '0' },
        fontSize: 20,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: { pb: '40', pl: '40', pr: '40', pt: '40' },
      avatarImageUrl: 'https://static.kolable.com/images/demo/home/icon-thumb.svg',
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#9b9b9b',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: '1-5QQ92_pD',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  rW2v9GmigE: {
    type: { resolvedName: 'CraftLayout' },
    nodes: ['bYgcKL5UAi', 'AtE_Tn_6G3', 'DfHQujh90U'],
    props: {
      id: 'CraftLayout',
      mobile: { margin: { ml: '16', mr: '16' }, columnRatio: [12], columnAmount: 1, displayAmount: 6 },
      desktop: { margin: { ml: '120', mr: '120' }, columnRatio: [4, 4, 4], columnAmount: 3, displayAmount: 6 },
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'RydfSkPn0x',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  xh0VGyR3UK: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['I2pPTe9ShY'],
    props: {
      id: 'CraftSection',
      margin: { mb: 1, ml: '0', mr: '0', mt: '0' },
      padding: { pb: 64, pl: '0', pr: '0', pt: 64 },
      coverUrl: 'https://i.picsum.photos/id/166/1920/1080.jpg?hmac=jxymCPYDSY6wglfW8ri3zwn-OgzKS9Kj5XdTHcbpnCk',
      backgroundType: 'backgroundImage',
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  xt2ekQJFhT: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['WTOZ7XwBcE'],
    props: {
      id: 'CraftSection',
      margin: { mb: 5, ml: '0', mr: '0', mt: '0' },
      padding: { pb: 64, pl: '0', pr: '0', pt: 64 },
      solidColor: '#f7f8f8',
      backgroundType: 'solidColor',
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  z61MeqQqwu: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['KizdarCnYR', 'E3wHkNuNAF'],
    props: { margin: {} },
    custom: { button: { label: 'deleteBlock' } },
    hidden: false,
    parent: 'WTOZ7XwBcE',
    isCanvas: false,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  zvFuLfkDoN: {
    type: { resolvedName: 'CraftSection' },
    nodes: ['_tAodfFvu7', 'OMIH3jlA6O'],
    props: {
      id: 'CraftSection',
      margin: { mb: '0', ml: '0', mr: '0', mt: '0' },
      padding: { pb: 64, pl: '0', pr: '0', pt: 64 },
      solidColor: '#4C5B8F',
      backgroundType: 'solidColor',
    },
    custom: { button: { label: 'deleteAllBlock' } },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
}

export const templateB = {
  ROOT: {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: [
      'AN590c6qsa',
      'saVMW9vtv-',
      'WBU-CKpIwk',
      '9zEySw6IsN',
      '24ksSCiKpk',
      'EfZnm3aKa5',
      'TqKwtP7Shv',
      'A_jEGcFtsX',
    ],
    props: {
      margin: {
        mb: '0',
        ml: '0',
        mr: '0',
        mt: '0',
      },
      padding: {
        pb: 1,
        pl: '0',
        pr: '0',
        pt: '0',
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  '-9ls3wLc5P': {
    type: {
      resolvedName: 'CraftCard',
    },
    nodes: [],
    props: {
      type: 'feature',
      title: '特色標題 1',
      variant: 'none',
      imageUrl: 'https://static.kolable.com/images/demo/home/icon-thumb-blue.svg',
      imageType: 'image',
      cardMargin: {},
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: {
          mb: '0',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: '25',
        pl: '25',
        pr: '25',
        pt: '25',
      },
      imageMargin: {
        mr: '16',
      },
      flexDirection: 'row',
      backgroundType: 'solidColor',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'EO-TgFRmYH',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  '-UAAaJBF0q': {
    type: {
      resolvedName: 'CraftCard',
    },
    nodes: [],
    props: {
      type: 'referrerReverse',
      title: '行政助理',
      variant: 'none',
      imageUrl: '',
      imageType: 'none',
      paragraph:
        '本身非本科畢業，對於設計的知識和技能都是靠零散的自學，但一直沒有融會貫通的感覺，經過老師由淺入深的講解和數個範例練習，重新幫我建構設計的觀念，很適合想踏入這個領遇卻不知道從何開始的人學習！',
      avatarName: '熙雯',
      avatarType: 'image',
      cardMargin: {},
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: {
          mb: '12',
          mt: '16',
        },
        fontSize: 20,
        textAlign: 'center',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: '40',
        pl: '40',
        pr: '40',
        pt: '40',
      },
      avatarImageUrl: 'https://static.kolable.com/images/demo/home/icon-thumb.svg',
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#9b9b9b',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'P-rPzPFVWW',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  '-udbODIgwN': {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: '#585858',
      margin: {
        mb: '40',
      },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '線上課程',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'WBU-CKpIwk',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  '0mtO6zzdh9': {
    type: {
      resolvedName: 'CraftCard',
    },
    nodes: [],
    props: {
      type: 'referrerReverse',
      title: '公務員',
      variant: 'none',
      imageUrl: '',
      imageType: 'none',
      paragraph:
        '我原是從事公務人員的相關工作，在職訓局上過一期的網頁課，就開始從事網頁工作，覺得自己有很多不足之處，但又不知從何學起，自行看書也覺所學有限，學習網頁資源國外相對較多，但無奈英文不好，爬文的很累。好在看到這門課程，從基礎靜態網頁到進階的互動網頁，都有詳細又美觀的示範案例，很推薦所有對網頁有興趣的朋友。',
      avatarName: '阿公',
      avatarType: 'image',
      cardMargin: {},
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: {
          mb: '12',
          mt: '16',
        },
        fontSize: 20,
        textAlign: 'center',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: '40',
        pl: '40',
        pr: '40',
        pt: '40',
      },
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#9b9b9b',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'P-rPzPFVWW',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  '1Xhguc89Aj': {
    type: {
      resolvedName: 'CraftLayout',
    },
    nodes: ['hjUj6UxdiG', 'w82fUHNnFT', '7hi64VTbYj'],
    props: {
      id: 'CraftLayout',
      mobile: {
        margin: {
          mb: '0',
          ml: 20,
          mr: 20,
          mt: '0',
        },
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 2,
      },
      desktop: {
        margin: {
          mb: '0',
          ml: 200,
          mr: 200,
          mt: '0',
        },
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 3,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'TqKwtP7Shv',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  '24ksSCiKpk': {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['lEAGAo_EWx', 'RaPDpAmVV3'],
    props: {
      id: 'CraftSection',
      margin: {
        mb: '5',
      },
      padding: {
        pb: '64',
        pt: '64',
      },
      coverUrl: 'https://i.picsum.photos/id/166/1920/1080.jpg?hmac=jxymCPYDSY6wglfW8ri3zwn-OgzKS9Kj5XdTHcbpnCk',
      backgroundType: 'backgroundImage',
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  '4Vqk4df38q': {
    type: {
      resolvedName: 'CraftCard',
    },
    nodes: [],
    props: {
      type: 'feature',
      title: '特色標題 3',
      variant: 'none',
      imageUrl: 'https://static.kolable.com/images/demo/home/icon-thumb-blue.svg',
      imageType: 'image',
      cardMargin: {},
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: {
          mb: '0',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: '25',
        pl: '25',
        pr: '25',
        pt: '25',
      },
      imageMargin: {
        mr: '16',
      },
      flexDirection: 'row',
      backgroundType: 'solidColor',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'EO-TgFRmYH',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  '5N_pv9J7s3': {
    type: {
      resolvedName: 'CraftLayout',
    },
    nodes: ['cvBhM0X5xV', 'Qu9avLzfS5', 'fdh4owWlCx'],
    props: {
      id: 'CraftLayout',
      mobile: {
        margin: {
          ml: '20',
          mr: '20',
        },
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 3,
      },
      desktop: {
        margin: {
          ml: '200',
          mr: '200',
        },
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 3,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'A_jEGcFtsX',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  '5XRb8t0YDD': {
    type: {
      resolvedName: 'CraftInstructor',
    },
    nodes: [],
    props: {
      appId: 'demo',
    },
    custom: {},
    hidden: false,
    parent: '9zEySw6IsN',
    isCanvas: false,
    displayName: 'CraftInstructor',
    linkedNodes: {},
  },
  '7hi64VTbYj': {
    type: {
      resolvedName: 'CraftCollapse',
    },
    nodes: [],
    props: {
      id: 'CraftCollapse3',
      title: '可以問老師問題嗎？',
      variant: 'none',
      paragraph:
        '網站的「線上課程」都可以隨時隨地透過電腦、手機、平板觀看購買後的課程影片，沒有時間和地點的限制！ 都可以隨時隨地透過電腦手機平板觀看購買後的課程影片沒有時間和地點的限制',
      cardMargin: {
        mt: '-15',
      },
      titleStyle: {
        color: '#585858',
        margin: {
          mb: '0',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: '20',
        pl: '20',
        pr: '20',
        pt: '20',
      },
      backgroundType: 'none',
      paragraphStyle: {
        color: '#585858',
        margin: {
          mt: '20',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '1Xhguc89Aj',
    isCanvas: true,
    displayName: 'CraftCollapse',
    linkedNodes: {},
  },
  '9zEySw6IsN': {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['C0ar-CG-ob', '5XRb8t0YDD'],
    props: {
      id: 'CraftSection',
      margin: {
        mb: 5,
        ml: '0',
        mr: '0',
        mt: '0',
      },
      padding: {
        pb: 64,
        pl: 120,
        pr: 120,
        pt: 64,
      },
      backgroundType: 'none',
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  AN590c6qsa: {
    type: {
      resolvedName: 'CraftCarousel',
    },
    nodes: [],
    props: {
      type: 'normal',
      covers: [
        {
          link: '/programs',
          title: '換個方式說溝通更有效',
          paragraph:
            '生命的目的是盡可能多地成為你自己，將你天生的才能和能力與你生活經驗中的智慧結合起來，並將它們與你內在的精神融合在一起，然後把自己作為禮物送回世界。',
          openNewTab: false,
          mobileCoverUrl: 'https://static.kolable.com/images/demo/cover-01-m.png',
          desktopCoverUrl: 'https://static.kolable.com/images/demo/cover-01.png',
        },
        {
          link: '',
          title: '',
          paragraph: '',
          openNewTab: false,
          mobileCoverUrl: 'https://static.kolable.com/images/demo/cover-02-m.jpg',
          desktopCoverUrl: 'https://static.kolable.com/images/demo/cover-02.jpg',
        },
      ],
      titleStyle: {
        color: '#ffffff',
        margin: {
          mb: '0',
          ml: '0',
          mr: '0',
          mt: '0',
        },
        fontSize: 26,
        textAlign: 'center',
        fontWeight: 'bold',
      },
      paragraphStyle: {
        color: '#ffffff',
        margin: {
          mb: '0',
          ml: '0',
          mr: '0',
          mt: '0',
        },
        fontSize: 16,
        textAlign: 'center',
        fontWeight: 'normal',
        lineHeight: 1.5,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'CraftCarousel',
    linkedNodes: {},
  },
  A_jEGcFtsX: {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['5N_pv9J7s3'],
    props: {
      id: 'CraftSection',
      margin: {
        mb: '5',
      },
      padding: {
        pb: '64',
        pt: '64',
      },
      coverUrl: 'https://i.picsum.photos/id/166/1920/1080.jpg?hmac=jxymCPYDSY6wglfW8ri3zwn-OgzKS9Kj5XdTHcbpnCk',
      backgroundType: 'backgroundImage',
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  'C0ar-CG-ob': {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: '#585858',
      margin: {
        mb: '25',
      },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '專業師資',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '9zEySw6IsN',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  'EO-TgFRmYH': {
    type: {
      resolvedName: 'CraftLayout',
    },
    nodes: ['-9ls3wLc5P', 'srHvNjfnsn', '4Vqk4df38q', 'L5muBFrMAM'],
    props: {
      id: 'CraftLayout',
      mobile: {
        margin: {
          ml: '16',
          mr: '16',
        },
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 4,
      },
      desktop: {
        margin: {
          ml: '60',
          mr: '60',
        },
        columnRatio: [3, 3, 3, 3],
        columnAmount: 4,
        displayAmount: 4,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'saVMW9vtv-',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  EfZnm3aKa5: {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['OPsNF1CgAr', 'P-rPzPFVWW'],
    props: {
      id: 'CraftSection',
      margin: {
        mb: 5,
        ml: '0',
        mr: '0',
        mt: '0',
      },
      padding: {
        pb: '0',
        pl: '0',
        pr: '0',
        pt: 64,
      },
      backgroundType: 'none',
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  'HYhW-sqnod': {
    type: {
      resolvedName: 'CraftStatistics',
    },
    nodes: [],
    props: {
      type: 'image',
      title: {
        color: 'white',
        margin: {
          mb: '16',
        },
        fontSize: 40,
        textAlign: 'center',
        fontWeight: 'normal',
        titleContent: '353+',
      },
      margin: {},
      padding: {
        pb: '10',
        pt: '10',
      },
      coverUrl: 'https://static.kolable.com/images/demo/home/icon-savetime-white.svg',
      paragraph: {
        color: 'white',
        margin: {},
        fontSize: 14,
        textAlign: 'center',
        fontWeight: 'lighter',
        paragraphContent: '覺得超有效',
      },
    },
    custom: {},
    hidden: false,
    parent: 'RaPDpAmVV3',
    isCanvas: false,
    displayName: 'CraftStatistics',
    linkedNodes: {},
  },
  L25BpKazPX: {
    type: {
      resolvedName: 'CraftCard',
    },
    nodes: [],
    props: {
      type: 'referrerReverse',
      title: '學生',
      variant: 'none',
      imageUrl: '',
      imageType: 'none',
      paragraph:
        '前面程式的課程，經過老師由淺入深的講解和數個範例練習，重新幫我建構了網頁設計的觀念，讓我得以將以前那些片段的知識都串接起來並賦予意義，就好像建立了系統性的架構，瞬間有豁然開朗的感覺。',
      avatarName: '阿生',
      avatarType: 'image',
      cardMargin: {},
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: {
          mb: '12',
          mt: '16',
        },
        fontSize: 20,
        textAlign: 'center',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: '40',
        pl: '40',
        pr: '40',
        pt: '40',
      },
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#9b9b9b',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'P-rPzPFVWW',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  L5muBFrMAM: {
    type: {
      resolvedName: 'CraftCard',
    },
    nodes: [],
    props: {
      type: 'feature',
      title: '特色標題 4',
      variant: 'none',
      imageUrl: 'https://static.kolable.com/images/demo/home/icon-thumb-blue.svg',
      imageType: 'image',
      cardMargin: {},
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: {
          mb: '0',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: '25',
        pl: '25',
        pr: '25',
        pt: '25',
      },
      imageMargin: {
        mr: '16',
      },
      flexDirection: 'row',
      backgroundType: 'solidColor',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'EO-TgFRmYH',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  NtxPBJVrkH: {
    type: {
      resolvedName: 'CraftLayout',
    },
    nodes: ['Vyg85h9FYN'],
    props: {
      id: 'CraftLayout',
      mobile: {
        margin: {
          mb: '20',
          ml: '16',
          mr: '16',
        },
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 3,
      },
      desktop: {
        margin: {
          mb: '20',
          ml: '120',
          mr: '120',
        },
        columnRatio: [4, 4, 4],
        columnAmount: 3,
        displayAmount: 3,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'WBU-CKpIwk',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  OPsNF1CgAr: {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: '#585858',
      margin: {
        mb: '25',
      },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '推薦評價',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'EfZnm3aKa5',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  'P-rPzPFVWW': {
    type: {
      resolvedName: 'CraftCarousel',
    },
    nodes: ['0mtO6zzdh9', '-UAAaJBF0q', 'L25BpKazPX'],
    props: {
      id: 'CraftCarousel',
      mobile: {
        arrows: true,
        margin: {
          mb: '0',
          ml: '16',
          mr: '16',
          mt: '0',
        },
        slidesToShow: 1,
        swipeToSlide: true,
        slidesToScroll: 1,
      },
      desktop: {
        arrows: true,
        margin: {
          mb: '0',
          ml: '20',
          mr: '20',
          mt: '0',
        },
        slidesToShow: 3,
        swipeToSlide: true,
        slidesToScroll: 1,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'EfZnm3aKa5',
    isCanvas: true,
    displayName: 'CraftCarousel',
    linkedNodes: {},
  },
  Qu9avLzfS5: {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: 'white',
      margin: {
        mb: 10,
        ml: '0',
        mr: '0',
        mt: '0',
      },
      fontSize: 16,
      textAlign: 'center',
      fontWeight: 'lighter',
      titleContent: '聽覺傳遞雖然最快，但視覺傳遞才最清楚，溝通 兵器，我選設計！',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '5N_pv9J7s3',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  RaPDpAmVV3: {
    type: {
      resolvedName: 'CraftLayout',
    },
    nodes: ['tqFhOqEMdR', 'aE1pV4YC5b', 'HYhW-sqnod', 'TalSUIX1SB'],
    props: {
      id: 'CraftLayout',
      mobile: {
        margin: {},
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 4,
      },
      desktop: {
        margin: {},
        columnRatio: [3, 3, 3, 3],
        columnAmount: 4,
        displayAmount: 4,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: '24ksSCiKpk',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  TalSUIX1SB: {
    type: {
      resolvedName: 'CraftStatistics',
    },
    nodes: [],
    props: {
      type: 'image',
      title: {
        color: 'white',
        margin: {
          mb: '16',
        },
        fontSize: 40,
        textAlign: 'center',
        fontWeight: 'normal',
        titleContent: '666+',
      },
      margin: {},
      padding: {
        pb: '10',
        pt: '10',
      },
      coverUrl: 'https://static.kolable.com/images/demo/home/icon-thumb-white.svg',
      paragraph: {
        color: 'white',
        margin: {},
        fontSize: 14,
        textAlign: 'center',
        fontWeight: 'lighter',
        paragraphContent: '覺得超省時間',
      },
    },
    custom: {},
    hidden: false,
    parent: 'RaPDpAmVV3',
    isCanvas: false,
    displayName: 'CraftStatistics',
    linkedNodes: {},
  },
  TqKwtP7Shv: {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['dd5A5hn2wI', '1Xhguc89Aj'],
    props: {
      id: 'CraftSection',
      margin: {
        mb: '5',
      },
      padding: {
        pb: '64',
        pt: '64',
      },
      backgroundType: 'none',
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  Vyg85h9FYN: {
    type: {
      resolvedName: 'CraftProgram',
    },
    nodes: [],
    props: {},
    custom: {},
    hidden: false,
    parent: 'NtxPBJVrkH',
    isCanvas: false,
    displayName: 'CraftProgram',
    linkedNodes: {},
  },
  'WBU-CKpIwk': {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['-udbODIgwN', 'NtxPBJVrkH', 'h3PXKv0k9R'],
    props: {
      id: 'CraftSection',
      margin: {
        mb: 5,
        ml: '0',
        mr: '0',
        mt: '0',
      },
      padding: {
        pb: 64,
        pl: '0',
        pr: '0',
        pt: 64,
      },
      backgroundType: 'none',
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  XhlpkAeouR: {
    type: {
      resolvedName: 'CraftButton',
    },
    nodes: [],
    props: {
      link: '/programs',
      size: 'md',
      block: false,
      color: '#4C5B8F',
      title: '馬上查看 〉',
      variant: 'text',
      openNewTab: false,
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'h3PXKv0k9R',
    isCanvas: false,
    displayName: 'CraftButton',
    linkedNodes: {},
  },
  aE1pV4YC5b: {
    type: {
      resolvedName: 'CraftStatistics',
    },
    nodes: [],
    props: {
      type: 'image',
      title: {
        color: 'white',
        margin: {
          mb: '16',
        },
        fontSize: 40,
        textAlign: 'center',
        fontWeight: 'normal',
        titleContent: '999+',
      },
      margin: {},
      padding: {
        pb: '10',
        pt: '10',
      },
      coverUrl: 'https://static.kolable.com/images/demo/home/icon-thumb-white.svg',
      paragraph: {
        color: 'white',
        margin: {},
        fontSize: 14,
        textAlign: 'center',
        fontWeight: 'lighter',
        paragraphContent: '覺得超省時間',
      },
    },
    custom: {},
    hidden: false,
    parent: 'RaPDpAmVV3',
    isCanvas: false,
    displayName: 'CraftStatistics',
    linkedNodes: {},
  },
  cvBhM0X5xV: {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: 'white',
      margin: {
        mb: '0',
        ml: '0',
        mr: '0',
        mt: '0',
      },
      fontSize: 28,
      textAlign: 'center',
      fontWeight: 'normal',
      titleContent: '還在等什麼？立即加入會員',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '5N_pv9J7s3',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  dd5A5hn2wI: {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: '#585858',
      margin: {
        mb: '40',
      },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '常見問題',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'TqKwtP7Shv',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  fdh4owWlCx: {
    type: {
      resolvedName: 'CraftButton',
    },
    nodes: [],
    props: {
      link: '/',
      size: 'lg',
      block: false,
      color: '#fff',
      title: '前往註冊',
      variant: 'outline',
      openNewTab: false,
      outlineColor: '#fff',
      backgroundType: 'none',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '5N_pv9J7s3',
    isCanvas: false,
    displayName: 'CraftButton',
    linkedNodes: {},
  },
  h3PXKv0k9R: {
    type: 'div',
    nodes: ['XhlpkAeouR'],
    props: {
      style: {
        textAlign: 'center',
      },
    },
    custom: {},
    hidden: false,
    parent: 'WBU-CKpIwk',
    isCanvas: false,
    displayName: 'div',
    linkedNodes: {},
  },
  hjUj6UxdiG: {
    type: {
      resolvedName: 'CraftCollapse',
    },
    nodes: [],
    props: {
      id: 'CraftCollapse1',
      title: '什麼是線上課程? 請問在哪裡上課？上課時間？',
      variant: 'none',
      paragraph:
        '網站的「線上課程」都可以隨時隨地透過電腦、手機、平板觀看購買後的課程影片，沒有時間和地點的限制！ 都可以隨時隨地透過電腦手機平板觀看購買後的課程影片沒有時間和地點的限制',
      cardMargin: {},
      titleStyle: {
        color: '#585858',
        margin: {
          mb: '0',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: '20',
        pl: '20',
        pr: '20',
        pt: '20',
      },
      backgroundType: 'none',
      paragraphStyle: {
        color: '#585858',
        margin: {
          mt: '20',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '1Xhguc89Aj',
    isCanvas: true,
    displayName: 'CraftCollapse',
    linkedNodes: {},
  },
  lEAGAo_EWx: {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: 'white',
      margin: {
        mb: '25',
      },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '提供完善的服務',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '24ksSCiKpk',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  'saVMW9vtv-': {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['EO-TgFRmYH'],
    props: {
      id: 'CraftSection',
      margin: {
        mb: 5,
        ml: '0',
        mr: '0',
        mt: '0',
      },
      padding: {
        pb: 32,
        pl: '0',
        pr: '0',
        pt: 64,
      },
      backgroundType: 'none',
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  srHvNjfnsn: {
    type: {
      resolvedName: 'CraftCard',
    },
    nodes: [],
    props: {
      type: 'feature',
      title: '特色標題 2',
      variant: 'none',
      imageUrl: 'https://static.kolable.com/images/demo/home/icon-thumb-blue.svg',
      imageType: 'image',
      cardMargin: {},
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: {
          mb: '0',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: '25',
        pl: '25',
        pr: '25',
        pt: '25',
      },
      imageMargin: {
        mr: '16',
      },
      flexDirection: 'row',
      backgroundType: 'solidColor',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'EO-TgFRmYH',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  tqFhOqEMdR: {
    type: {
      resolvedName: 'CraftStatistics',
    },
    nodes: [],
    props: {
      type: 'image',
      title: {
        color: 'white',
        margin: {
          mb: '16',
        },
        fontSize: 40,
        textAlign: 'center',
        fontWeight: 'normal',
        titleContent: '814+',
      },
      margin: {},
      padding: {
        pb: '10',
        pt: '10',
      },
      coverUrl: 'https://static.kolable.com/images/demo/home/icon-savetime-white.svg',
      paragraph: {
        color: 'white',
        margin: {},
        fontSize: 14,
        textAlign: 'center',
        fontWeight: 'lighter',
        paragraphContent: '覺得超有效',
      },
    },
    custom: {},
    hidden: false,
    parent: 'RaPDpAmVV3',
    isCanvas: false,
    displayName: 'CraftStatistics',
    linkedNodes: {},
  },
  w82fUHNnFT: {
    type: {
      resolvedName: 'CraftCollapse',
    },
    nodes: [],
    props: {
      id: 'CraftCollapse2',
      title: '課程可以看幾次？',
      variant: 'none',
      paragraph:
        '網站的「線上課程」都可以隨時隨地透過電腦、手機、平板觀看購買後的課程影片，沒有時間和地點的限制！ 都可以隨時隨地透過電腦手機平板觀看購買後的課程影片沒有時間和地點的限制',
      cardMargin: {
        mt: '-15',
      },
      titleStyle: {
        color: '#585858',
        margin: {
          mb: '0',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: '20',
        pl: '20',
        pr: '20',
        pt: '20',
      },
      backgroundType: 'none',
      paragraphStyle: {
        color: '#585858',
        margin: {
          mt: '20',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '1Xhguc89Aj',
    isCanvas: true,
    displayName: 'CraftCollapse',
    linkedNodes: {},
  },
}

export const templateC = {
  ROOT: {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['AN590c6qsa', 'WBU-CKpIwk', 'qTkIQll-L4', 'RydfSkPn0x', 'kMxH8VLY56', '_lBgDL7dCy', '1WDRk7AKtd'],
    props: {
      margin: {
        mb: '0',
        ml: '0',
        mr: '0',
        mt: '0',
      },
      padding: {
        pb: 1,
        pl: '0',
        pr: '0',
        pt: '0',
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  '-udbODIgwN': {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: '#585858',
      margin: {
        mb: '40',
      },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '線上課程',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'WBU-CKpIwk',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  '0-czz5kqN4': {
    type: {
      resolvedName: 'CraftTitleAndParagraph',
    },
    nodes: [],
    props: {
      title: {
        color: '#4c5b8f',
        border: {
          borderLeftColor: '#4c5b8f',
          borderLeftStyle: 'solid',
          borderLeftWidth: '4',
        },
        margin: {
          mb: '13',
        },
        padding: {
          pb: '2',
          pl: '8',
          pt: '2',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        titleContent: '你們跟坊間的其他課程有什麼不一樣？',
      },
      paragraph: {
        color: '#585858',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'lighter',
        lineHeight: 1.69,
        paragraphContent:
          '在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一',
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '5LTmO3G2md',
    isCanvas: false,
    displayName: 'CraftTitleAndParagraph',
    linkedNodes: {},
  },
  '1WDRk7AKtd': {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['7paCnVo9Wm', '5LTmO3G2md'],
    props: {
      id: 'CraftSection',
      margin: {
        mb: '5',
      },
      padding: {
        pb: '64',
        pt: '64',
      },
      backgroundType: 'none',
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  '2QgJ7idVr3': {
    type: {
      resolvedName: 'CraftTitleAndParagraph',
    },
    nodes: [],
    props: {
      title: {
        color: '#4c5b8f',
        border: {
          borderLeftColor: '#4c5b8f',
          borderLeftStyle: 'solid',
          borderLeftWidth: '4',
        },
        margin: {
          mb: '13',
        },
        padding: {
          pb: '2',
          pl: '8',
          pt: '2',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        titleContent: '完成暖身課程大約需要花多少時間？',
      },
      paragraph: {
        color: '#585858',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'lighter',
        lineHeight: 1.69,
        paragraphContent:
          '在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一',
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '5LTmO3G2md',
    isCanvas: false,
    displayName: 'CraftTitleAndParagraph',
    linkedNodes: {},
  },
  '5LTmO3G2md': {
    type: {
      resolvedName: 'CraftLayout',
    },
    nodes: ['WNFe1jLA1Y', '0-czz5kqN4', 'qj1uGTHiDW', '2QgJ7idVr3', 'U-jhMwjmMm'],
    props: {
      id: 'CraftLayout',
      mobile: {
        margin: {
          ml: '20',
          mr: '20',
        },
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 5,
      },
      desktop: {
        margin: {
          ml: '200',
          mr: '200',
        },
        columnRatio: [6, 6],
        columnAmount: 2,
        displayAmount: 5,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: '1WDRk7AKtd',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  '5PKF9nNWuF': {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: 'white',
      margin: {
        mb: '0',
        ml: '0',
        mr: '0',
        mt: '0',
      },
      fontSize: 28,
      textAlign: 'center',
      fontWeight: 'normal',
      titleContent: '還在等什麼？立即加入會員',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '_OJG0FI7zR',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  '7paCnVo9Wm': {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: '#585858',
      margin: {
        mb: '40',
      },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '常見問題',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '1WDRk7AKtd',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  '9XLFTX_CuW': {
    type: {
      resolvedName: 'CraftCarousel',
    },
    nodes: ['NV5wqyM95m', 'Pam2jqgyk_', 'dHZesgxq1V'],
    props: {
      id: 'CraftCarousel',
      mobile: {
        arrows: true,
        margin: {
          mb: '0',
          ml: '16',
          mr: '16',
          mt: '0',
        },
        slidesToShow: 1,
        swipeToSlide: true,
        slidesToScroll: 1,
      },
      desktop: {
        arrows: true,
        margin: {
          mb: '0',
          ml: '20',
          mr: '20',
          mt: '0',
        },
        slidesToShow: 3,
        swipeToSlide: true,
        slidesToScroll: 1,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'kMxH8VLY56',
    isCanvas: true,
    displayName: 'CraftCarousel',
    linkedNodes: {},
  },
  AN590c6qsa: {
    type: {
      resolvedName: 'CraftCarousel',
    },
    nodes: [],
    props: {
      type: 'normal',
      covers: [
        {
          link: '/programs',
          title: '換個方式說溝通更有效',
          paragraph:
            '生命的目的是盡可能多地成為你自己，將你天生的才能和能力與你生活經驗中的智慧結合起來，並將它們與你內在的精神融合在一起，然後把自己作為禮物送回世界。',
          openNewTab: false,
          mobileCoverUrl: 'https://static.kolable.com/images/demo/cover-01-m.png',
          desktopCoverUrl: 'https://static.kolable.com/images/demo/cover-01.png',
        },
        {
          link: '',
          title: '',
          paragraph: '',
          openNewTab: false,
          mobileCoverUrl: 'https://static.kolable.com/images/demo/cover-02-m.jpg',
          desktopCoverUrl: 'https://static.kolable.com/images/demo/cover-02.jpg',
        },
      ],
      titleStyle: {
        color: '#ffffff',
        margin: {
          mb: '0',
          ml: '0',
          mr: '0',
          mt: '0',
        },
        fontSize: 26,
        textAlign: 'center',
        fontWeight: 'bold',
      },
      paragraphStyle: {
        color: '#ffffff',
        margin: {
          mb: '0',
          ml: '0',
          mr: '0',
          mt: '0',
        },
        fontSize: 16,
        textAlign: 'center',
        fontWeight: 'normal',
        lineHeight: 1.5,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'CraftCarousel',
    linkedNodes: {},
  },
  AtE_Tn_6G3: {
    type: {
      resolvedName: 'CraftCard',
    },
    nodes: [],
    props: {
      type: 'featureWithParagraph',
      title: '特色標題',
      variant: 'backgroundColor',
      imageUrl: 'https://static.kolable.com/images/demo/home/icon-thumb-blue.svg',
      imageType: 'image',
      paragraph: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
      cardMargin: {
        mb: '0',
        ml: '0',
        mr: '0',
        mt: '0',
      },
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: {
          mb: 8,
          ml: '0',
          mr: '0',
          mt: '0',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: 32,
        pl: 32,
        pr: 32,
        pt: 32,
      },
      imageMargin: {
        mb: 16,
        ml: '0',
        mr: '0',
        mt: '0',
      },
      imagePadding: {
        pb: '0',
        pl: '0',
        pr: '0',
        pt: '0',
      },
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#585858',
        margin: {
          mb: '0',
          ml: '0',
          mr: 20,
          mt: '0',
        },
        fontSize: 14,
        textAlign: 'left',
        fontWeight: 'lighter',
        lineHeight: 1.57,
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'rW2v9GmigE',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  BlN5eu2A22: {
    type: {
      resolvedName: 'CraftLayout',
    },
    nodes: ['pw5wq5-wVE', 'g3vFe4riYG'],
    props: {
      id: 'CraftLayout',
      mobile: {
        margin: {},
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 2,
      },
      desktop: {
        margin: {
          ml: '200',
          mr: '200',
        },
        columnRatio: [4, 8],
        columnAmount: 2,
        displayAmount: 2,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'qTkIQll-L4',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  DfHQujh90U: {
    type: {
      resolvedName: 'CraftCard',
    },
    nodes: [],
    props: {
      type: 'featureWithParagraph',
      title: '特色標題',
      variant: 'backgroundColor',
      imageUrl: 'https://static.kolable.com/images/demo/home/icon-thumb-blue.svg',
      imageType: 'image',
      paragraph: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
      cardMargin: {
        mb: '0',
        ml: '0',
        mr: '0',
        mt: '0',
      },
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: {
          mb: 8,
          ml: '0',
          mr: '0',
          mt: '0',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: 32,
        pl: 32,
        pr: 32,
        pt: 32,
      },
      imageMargin: {
        mb: 16,
        ml: '0',
        mr: '0',
        mt: '0',
      },
      imagePadding: {
        pb: '0',
        pl: '0',
        pr: '0',
        pt: '0',
      },
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#585858',
        margin: {
          mb: '0',
          ml: '0',
          mr: 20,
          mt: '0',
        },
        fontSize: 14,
        textAlign: 'left',
        fontWeight: 'lighter',
        lineHeight: 1.57,
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'rW2v9GmigE',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  HemvuPuzKv: {
    type: {
      resolvedName: 'CraftLayout',
    },
    nodes: ['N7-sRa7O-9', 'N4lw7VCo9_', 'QRj-EVLVyO'],
    props: {
      id: 'CraftLayout',
      mobile: {
        margin: {},
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 3,
      },
      desktop: {
        margin: {
          ml: '30',
          mr: '30',
        },
        columnRatio: [4, 4, 4],
        columnAmount: 3,
        displayAmount: 3,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'g3vFe4riYG',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  Hlokdj0WsE: {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: '#585858',
      margin: {
        mb: 40,
        ml: '0',
        mr: '0',
        mt: '0',
      },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '三大特色',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'RydfSkPn0x',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  N4lw7VCo9_: {
    type: {
      resolvedName: 'CraftStatistics',
    },
    nodes: [],
    props: {
      type: 'image',
      title: {
        color: '#4C5B8F',
        margin: {
          mb: '16',
        },
        fontSize: 40,
        textAlign: 'center',
        fontWeight: 'normal',
        titleContent: '999+',
      },
      margin: {},
      padding: {
        pb: '10',
        pt: '10',
      },
      paragraph: {
        color: '#585858',
        margin: {},
        fontSize: 14,
        textAlign: 'center',
        fontWeight: 'lighter',
        paragraphContent: '覺得超省時間',
      },
    },
    custom: {},
    hidden: false,
    parent: 'HemvuPuzKv',
    isCanvas: false,
    displayName: 'CraftStatistics',
    linkedNodes: {},
  },
  'N7-sRa7O-9': {
    type: {
      resolvedName: 'CraftStatistics',
    },
    nodes: [],
    props: {
      type: 'image',
      title: {
        color: '#4C5B8F',
        margin: {
          mb: 16,
          ml: '0',
          mr: '0',
          mt: '0',
        },
        fontSize: 40,
        textAlign: 'center',
        fontWeight: 'normal',
        titleContent: '814+',
      },
      margin: {
        mb: '0',
        ml: '0',
        mr: 30,
        mt: '0',
      },
      padding: {
        pb: 10,
        pl: '0',
        pr: '0',
        pt: 10,
      },
      paragraph: {
        color: '#585858',
        margin: {
          mb: '0',
          ml: '0',
          mr: '0',
          mt: '0',
        },
        fontSize: 14,
        textAlign: 'center',
        fontWeight: 'lighter',
        paragraphContent: '覺得超有效',
      },
    },
    custom: {},
    hidden: false,
    parent: 'HemvuPuzKv',
    isCanvas: false,
    displayName: 'CraftStatistics',
    linkedNodes: {},
  },
  NV5wqyM95m: {
    type: {
      resolvedName: 'CraftCard',
    },
    nodes: [],
    props: {
      type: 'referrerReverse',
      title: '公務員',
      variant: 'none',
      imageUrl: '',
      imageType: 'none',
      paragraph:
        '我原是從事公務人員的相關工作，在職訓局上過一期的網頁課，就開始從事網頁工作，覺得自己有很多不足之處，但又不知從何學起，自行看書也覺所學有限，學習網頁資源國外相對較多，但無奈英文不好，爬文的很累。好在看到這門課程，從基礎靜態網頁到進階的互動網頁，都有詳細又美觀的示範案例，很推薦所有對網頁有興趣的朋友。',
      avatarName: '阿公',
      avatarType: 'image',
      cardMargin: {},
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: {
          mb: '12',
          mt: '16',
        },
        fontSize: 20,
        textAlign: 'center',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: '40',
        pl: '40',
        pr: '40',
        pt: '40',
      },
      backgroundType: 'none',
      paragraphStyle: {
        color: '#9b9b9b',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '9XLFTX_CuW',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  NtxPBJVrkH: {
    type: {
      resolvedName: 'CraftLayout',
    },
    nodes: ['Vyg85h9FYN'],
    props: {
      id: 'CraftLayout',
      mobile: {
        margin: {
          mb: '20',
          ml: '16',
          mr: '16',
        },
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 3,
      },
      desktop: {
        margin: {
          mb: '20',
          ml: '120',
          mr: '120',
        },
        columnRatio: [4, 4, 4],
        columnAmount: 3,
        displayAmount: 3,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'WBU-CKpIwk',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  Pam2jqgyk_: {
    type: {
      resolvedName: 'CraftCard',
    },
    nodes: [],
    props: {
      type: 'referrerReverse',
      title: '行政助理',
      variant: 'none',
      imageUrl: '',
      imageType: 'none',
      paragraph:
        '本身非本科畢業，對於設計的知識和技能都是靠零散的自學，但一直沒有融會貫通的感覺，經過老師由淺入深的講解和數個範例練習，重新幫我建構設計的觀念，很適合想踏入這個領遇卻不知道從何開始的人學習！',
      avatarName: '熙雯',
      avatarType: 'image',
      cardMargin: {},
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: {
          mb: '12',
          mt: '16',
        },
        fontSize: 20,
        textAlign: 'center',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: '40',
        pl: '40',
        pr: '40',
        pt: '40',
      },
      avatarImageUrl: 'https://static.kolable.com/images/demo/home/icon-thumb.svg',
      backgroundType: 'none',
      paragraphStyle: {
        color: '#9b9b9b',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '9XLFTX_CuW',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  'QRj-EVLVyO': {
    type: {
      resolvedName: 'CraftStatistics',
    },
    nodes: [],
    props: {
      type: 'image',
      title: {
        color: '#4C5B8F',
        margin: {
          mb: '16',
        },
        fontSize: 40,
        textAlign: 'center',
        fontWeight: 'normal',
        titleContent: '353+',
      },
      margin: {},
      padding: {
        pb: '10',
        pt: '10',
      },
      paragraph: {
        color: '#585858',
        margin: {},
        fontSize: 14,
        textAlign: 'center',
        fontWeight: 'lighter',
        paragraphContent: '覺得超有效',
      },
    },
    custom: {},
    hidden: false,
    parent: 'HemvuPuzKv',
    isCanvas: false,
    displayName: 'CraftStatistics',
    linkedNodes: {},
  },
  RydfSkPn0x: {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['Hlokdj0WsE', 'rW2v9GmigE'],
    props: {
      id: 'CraftSection',
      margin: {
        mb: 5,
        ml: '0',
        mr: '0',
        mt: '0',
      },
      padding: {
        pb: 64,
        pl: '0',
        pr: '0',
        pt: 64,
      },
      backgroundType: 'none',
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  TaN6Bbhzqn: {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: 'white',
      margin: {
        mb: 10,
        ml: '0',
        mr: '0',
        mt: '0',
      },
      fontSize: 16,
      textAlign: 'center',
      fontWeight: 'lighter',
      titleContent: '聽覺傳遞雖然最快，但視覺傳遞才最清楚，溝通 兵器，我選設計！',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '_OJG0FI7zR',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  'U-jhMwjmMm': {
    type: {
      resolvedName: 'CraftTitleAndParagraph',
    },
    nodes: [],
    props: {
      title: {
        color: '#4c5b8f',
        border: {
          borderLeftColor: '#4c5b8f',
          borderLeftStyle: 'solid',
          borderLeftWidth: '4',
        },
        margin: {
          mb: '13',
        },
        padding: {
          pb: '2',
          pl: '8',
          pt: '2',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        titleContent: '我已有相關基礎',
      },
      paragraph: {
        color: '#585858',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'lighter',
        lineHeight: 1.69,
        paragraphContent:
          '在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一',
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '5LTmO3G2md',
    isCanvas: false,
    displayName: 'CraftTitleAndParagraph',
    linkedNodes: {},
  },
  Vyg85h9FYN: {
    type: {
      resolvedName: 'CraftProgram',
    },
    nodes: [],
    props: {},
    custom: {},
    hidden: false,
    parent: 'NtxPBJVrkH',
    isCanvas: false,
    displayName: 'CraftProgram',
    linkedNodes: {},
  },
  'WBU-CKpIwk': {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['-udbODIgwN', 'NtxPBJVrkH', 'h3PXKv0k9R'],
    props: {
      id: 'CraftSection',
      margin: {
        mb: 5,
        ml: '0',
        mr: '0',
        mt: '0',
      },
      padding: {
        pb: 64,
        pl: '0',
        pr: '0',
        pt: 64,
      },
      backgroundType: 'none',
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  WNFe1jLA1Y: {
    type: {
      resolvedName: 'CraftTitleAndParagraph',
    },
    nodes: [],
    props: {
      title: {
        color: '#4c5b8f',
        border: {
          borderLeftColor: '#4c5b8f',
          borderLeftStyle: 'solid',
          borderLeftWidth: '4',
        },
        margin: {
          mb: '13',
        },
        padding: {
          pb: '2',
          pl: '8',
          pt: '2',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        titleContent: '完全沒有相關背景也可以學會嗎？',
      },
      paragraph: {
        color: '#585858',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'lighter',
        lineHeight: 1.69,
        paragraphContent:
          '在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一',
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '5LTmO3G2md',
    isCanvas: false,
    displayName: 'CraftTitleAndParagraph',
    linkedNodes: {},
  },
  XhlpkAeouR: {
    type: {
      resolvedName: 'CraftButton',
    },
    nodes: [],
    props: {
      link: '/programs',
      size: 'md',
      block: false,
      color: '#4C5B8F',
      title: '馬上查看 〉',
      variant: 'text',
      openNewTab: false,
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'h3PXKv0k9R',
    isCanvas: false,
    displayName: 'CraftButton',
    linkedNodes: {},
  },
  _OJG0FI7zR: {
    type: {
      resolvedName: 'CraftLayout',
    },
    nodes: ['5PKF9nNWuF', 'TaN6Bbhzqn', 'y4ZV1eG-RX'],
    props: {
      id: 'CraftLayout',
      mobile: {
        margin: {
          ml: '20',
          mr: '20',
        },
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 3,
      },
      desktop: {
        margin: {
          ml: '200',
          mr: '200',
        },
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 3,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: '_lBgDL7dCy',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  _lBgDL7dCy: {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['_OJG0FI7zR'],
    props: {
      id: 'CraftSection',
      margin: {
        mb: '5',
      },
      padding: {
        pb: '64',
        pt: '64',
      },
      coverUrl: 'https://i.picsum.photos/id/166/1920/1080.jpg?hmac=jxymCPYDSY6wglfW8ri3zwn-OgzKS9Kj5XdTHcbpnCk',
      backgroundType: 'backgroundImage',
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  bYgcKL5UAi: {
    type: {
      resolvedName: 'CraftCard',
    },
    nodes: [],
    props: {
      type: 'featureWithParagraph',
      title: '特色標題',
      variant: 'backgroundColor',
      imageUrl: 'https://static.kolable.com/images/demo/home/icon-thumb-blue.svg',
      imageType: 'image',
      paragraph: '遠程也能參與互動，用超低成本造成內容的最大效能，讓粉絲隨時隨地主動互動',
      cardMargin: {
        mb: '0',
        ml: '0',
        mr: '0',
        mt: '0',
      },
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: {
          mb: 8,
          ml: '0',
          mr: '0',
          mt: '0',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: 32,
        pl: 32,
        pr: 32,
        pt: 32,
      },
      imageMargin: {
        mb: 16,
        ml: '0',
        mr: '0',
        mt: '0',
      },
      imagePadding: {
        pb: '0',
        pl: '0',
        pr: '0',
        pt: '0',
      },
      backgroundType: 'solidColor',
      paragraphStyle: {
        color: '#585858',
        margin: {
          mb: '0',
          ml: '0',
          mr: 20,
          mt: '0',
        },
        fontSize: 14,
        textAlign: 'left',
        fontWeight: 'lighter',
        lineHeight: 1.57,
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'rW2v9GmigE',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  dHZesgxq1V: {
    type: {
      resolvedName: 'CraftCard',
    },
    nodes: [],
    props: {
      type: 'referrerReverse',
      title: '學生',
      variant: 'none',
      imageUrl: '',
      imageType: 'none',
      paragraph:
        '前面程式的課程，經過老師由淺入深的講解和數個範例練習，重新幫我建構了網頁設計的觀念，讓我得以將以前那些片段的知識都串接起來並賦予意義，就好像建立了系統性的架構，瞬間有豁然開朗的感覺。',
      avatarName: '阿生',
      avatarType: 'image',
      cardMargin: {},
      solidColor: 'white',
      titleStyle: {
        color: '#585858',
        margin: {
          mb: '12',
          mt: '16',
        },
        fontSize: 20,
        textAlign: 'center',
        fontWeight: 'bold',
      },
      cardPadding: {
        pb: '40',
        pl: '40',
        pr: '40',
        pt: '40',
      },
      backgroundType: 'none',
      paragraphStyle: {
        color: '#9b9b9b',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        lineHeight: 1.69,
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '9XLFTX_CuW',
    isCanvas: false,
    displayName: 'CraftCard',
    linkedNodes: {},
  },
  dL6GHtNHiP: {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: '#585858',
      margin: {
        mb: 15,
        ml: '0',
        mr: '0',
        mt: '0',
      },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '高品質的學習體驗',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'g3vFe4riYG',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  g3vFe4riYG: {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['dL6GHtNHiP', 'HemvuPuzKv'],
    props: {
      margin: {},
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'BlN5eu2A22',
    isCanvas: false,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  h3PXKv0k9R: {
    type: 'div',
    nodes: ['XhlpkAeouR'],
    props: {
      style: {
        textAlign: 'center',
      },
    },
    custom: {},
    hidden: false,
    parent: 'WBU-CKpIwk',
    isCanvas: false,
    displayName: 'div',
    linkedNodes: {},
  },
  kMxH8VLY56: {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['oeCLO33f-8', '9XLFTX_CuW'],
    props: {
      id: 'CraftSection',
      margin: {
        mb: '0',
        ml: '0',
        mr: '0',
        mt: '0',
      },
      padding: {
        pb: 64,
        pl: '0',
        pr: '0',
        pt: 64,
      },
      solidColor: '#f7f8f8',
      backgroundType: 'solidColor',
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  'oeCLO33f-8': {
    type: {
      resolvedName: 'CraftTitle',
    },
    nodes: [],
    props: {
      color: '#585858',
      margin: {
        mb: '25',
      },
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      titleContent: '推薦評價',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'kMxH8VLY56',
    isCanvas: false,
    displayName: 'CraftTitle',
    linkedNodes: {},
  },
  'pw5wq5-wVE': {
    type: {
      resolvedName: 'CraftImage',
    },
    nodes: [],
    props: {
      type: 'image',
      width: '100%',
      margin: {},
      padding: {},
      coverUrl: 'https://static.kolable.com/images/demo/home/feature-img2.jpg',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: 'BlN5eu2A22',
    isCanvas: false,
    displayName: 'CraftImage',
    linkedNodes: {},
  },
  'qTkIQll-L4': {
    type: {
      resolvedName: 'CraftSection',
    },
    nodes: ['BlN5eu2A22'],
    props: {
      id: 'CraftSection',
      margin: {
        mb: '5',
      },
      padding: {
        pb: '64',
        pt: '64',
      },
      backgroundType: 'none',
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: true,
    displayName: 'CraftSection',
    linkedNodes: {},
  },
  qj1uGTHiDW: {
    type: {
      resolvedName: 'CraftTitleAndParagraph',
    },
    nodes: [],
    props: {
      title: {
        color: '#4c5b8f',
        border: {
          borderLeftColor: '#4c5b8f',
          borderLeftStyle: 'solid',
          borderLeftWidth: '4',
        },
        margin: {
          mb: '13',
        },
        padding: {
          pb: '2',
          pl: '8',
          pt: '2',
        },
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'normal',
        titleContent: '我可以一邊工作、一邊上課嗎？',
      },
      paragraph: {
        color: '#585858',
        margin: {},
        fontSize: 16,
        textAlign: 'left',
        fontWeight: 'lighter',
        lineHeight: 1.69,
        paragraphContent:
          '在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一種服務在現時段是一',
      },
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '5LTmO3G2md',
    isCanvas: false,
    displayName: 'CraftTitleAndParagraph',
    linkedNodes: {},
  },
  rW2v9GmigE: {
    type: {
      resolvedName: 'CraftLayout',
    },
    nodes: ['bYgcKL5UAi', 'AtE_Tn_6G3', 'DfHQujh90U'],
    props: {
      id: 'CraftLayout',
      mobile: {
        margin: {
          ml: '16',
          mr: '16',
        },
        columnRatio: [12],
        columnAmount: 1,
        displayAmount: 6,
      },
      desktop: {
        margin: {
          ml: '120',
          mr: '120',
        },
        columnRatio: [4, 4, 4],
        columnAmount: 3,
        displayAmount: 6,
      },
    },
    custom: {
      button: {
        label: 'deleteAllBlock',
      },
    },
    hidden: false,
    parent: 'RydfSkPn0x',
    isCanvas: true,
    displayName: 'CraftLayout',
    linkedNodes: {},
  },
  'y4ZV1eG-RX': {
    type: {
      resolvedName: 'CraftButton',
    },
    nodes: [],
    props: {
      link: '/',
      size: 'md',
      block: false,
      color: '#fff',
      title: '前往註冊',
      variant: 'outline',
      openNewTab: false,
      outlineColor: '#fff',
      backgroundType: 'none',
    },
    custom: {
      button: {
        label: 'deleteBlock',
      },
    },
    hidden: false,
    parent: '_OJG0FI7zR',
    isCanvas: false,
    displayName: 'CraftButton',
    linkedNodes: {},
  },
}
