name: Deploy to S3

on:
  push:
    branches:
      - release
      - master

env:
  NODE_ENV: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.0
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install
        run: yarn install
      - name: Output ts version
        run: yarn tsc --version
      - name: Output packages version
        run: yarn list
      - name: Build
        run: yarn run build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ github.ref == 'refs/heads/master' && 'static.kolable.com' || 'static-dev.kolable.com' }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'build'
          DEST_DIR: deploys/${{ github.repository }}/${{ github.ref }}
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
