name: Deploy to S3

on:
  push:
    branches:
      - release
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jeanlescure/react-deploy-to-s3-action@main
        with:
          args: --follow-symlinks --delete
        env:
          NODE_ENV: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
          AWS_S3_BUCKET: ${{ github.ref == 'refs/heads/master' && 'static.kolable.com' || 'static-dev.kolable.com' }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: build
          DEST_DIR: deploys/${{ github.repository }}/${{ github.ref }}
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
